import { PEOPLE } from "../data/content.js";
import { badge, button, card, field, keyboardDemo, segmented } from "./components.js";
import { homeIcon } from "./home-icons.js";

const wordmark = `<div class="row" style="justify-content:center;margin:28px 0 12px"><span class="brand-dot">R</span><strong style="font-size:20px">RMA Delivery</strong></div>`;
const authHead = (step, title, copy) => `${wordmark}<div class="page-heading" style="text-align:center"><span class="eyebrow">เริ่มต้นใช้งาน · ${step}</span><h2>${title}</h2><p>${copy}</p></div>`;

export function renderAuth(id,ctx) {
  switch(id) {
    case "A-01": return `<div data-route="A-02" role="button" tabindex="0" aria-label="แตะเพื่อไปต่อ" style="cursor:pointer;min-height:670px;display:flex;flex-direction:column;justify-content:center;text-align:center;padding:18px">${wordmark}<div style="width:150px;height:150px;display:grid;place-items:center;margin:34px auto;border-radius:48px;background:linear-gradient(145deg,var(--brand),#8B79E6);color:#fff;box-shadow:var(--shadow)">${homeIcon("arrow",58)}</div><span class="eyebrow">อาหาร · เดินทาง · ชีวิตในเมือง</span><h2 style="font-size:29px;margin:6px 0">บริการใกล้ตัว<br>ในแอปเดียว</h2><div class="muted small" style="margin-top:28px">แตะเพื่อไปต่อ</div><div class="muted micro" style="margin-top:16px">กำลังตรวจสอบบัญชี...</div></div>`;
    case "A-02": return `${authHead("01 / 06","ทุกวันสะดวกขึ้น","สั่งอาหารและเดินทางได้ง่ายในแอปเดียว")}${card(`<div class="state-box" style="min-height:180px"><div><div class="state-illustration" style="margin:0 auto">${homeIcon("home",30)}</div><strong>ร้านโปรด ส่งถึงหน้าบ้าน</strong><p class="muted small">เชื่อมร้านในย่านและรายการอาหารที่คุณชอบ</p></div></div><div class="row-between" style="margin-top:14px"><span class="small">ภาษาแอป</span>${segmented([["th","ไทย"],["en","English"]], ctx.appLang||"th", "set-lang")}</div><div class="chip-list" style="justify-content:center;margin:12px"><span class="pill brand">1</span><span class="pill">2</span><span class="pill">3</span></div>`)}${button("ถัดไป",{route:"A-03"})}${button("ข้ามแนะนำ",{route:"A-03",variant:"ghost"})}`;
    case "A-03": return `${authHead("02 / 06","เข้าสู่ระบบ","กรอกเบอร์โทรศัพท์เพื่อรับรหัสยืนยัน")}${card(`${field("เบอร์โทรศัพท์", "08X XXX XXXX", "tel", "0812343278")}<div class="muted micro">เราจะส่งรหัส OTP เพื่อยืนยันตัวตน · ไม่มีค่าใช้จ่าย</div>${keyboardDemo()}`)}${button("รับรหัส OTP",{route:"A-04"})}${button("เข้าสู่ระบบด้วย LINE",{action:"line-login",variant:"secondary"})}<div class="muted micro" style="text-align:center;margin-top:14px">เมื่อดำเนินต่อ ถือว่าคุณยอมรับเงื่อนไขการใช้บริการและนโยบายความเป็นส่วนตัว</div>`;
    case "A-04": return `${authHead("03 / 06","ยืนยันเบอร์โทร","กรอกรหัส 6 หลักที่ส่งไปยัง 08x-xxx-3278")}${card(`<div class="row" style="justify-content:center;gap:7px;margin:22px 0">${[1,2,3,4,5,6].map((x,i)=>`<input class="field" aria-label="เลข OTP ${x}" maxlength="1" inputmode="numeric" value="${i===0?'1':i===1?'2':i===2?'3':i===3?'4':i===4?'5':'6'}" style="width:43px;height:54px;padding:0;text-align:center;font-size:22px;font-weight:700">`).join("")}</div><div class="muted small" style="text-align:center">ส่งรหัสใหม่ได้ใน <strong data-countdown>00:28</strong></div><button class="text-btn" data-action="resend-otp" data-resend disabled style="display:block;margin:8px auto">ส่งรหัสอีกครั้ง · 28 วินาที</button>`)}${button("ยืนยันรหัส",{route:"A-05"})}${button("เปลี่ยนเบอร์โทร",{route:"A-03",variant:"ghost"})}`;
    case "A-05": return `${authHead("04 / 06","ยินดีที่ได้รู้จัก","ตั้งค่าบัญชีของคุณก่อนเริ่มใช้บริการ")}${card(`${field("ชื่อ-นามสกุล", "ชื่อจริง นามสกุล", "text", PEOPLE.customer.name)}<label class="toggle-row"><span><input type="checkbox" data-consent="terms"> ยอมรับข้อกำหนดการใช้บริการ <button class="text-btn" type="button" data-action="show-terms">อ่านเอกสาร</button></span></label><label class="toggle-row"><span><input type="checkbox" data-consent="pdpa"> รับทราบประกาศความเป็นส่วนตัว (PDPA) <button class="text-btn" type="button" data-action="show-privacy">อ่านเอกสาร</button></span></label><div class="muted micro">คุณสามารถจัดการข้อมูลส่วนตัวและขอลบบัญชีได้จากเมนูบัญชี</div>`)}${button("ดำเนินการต่อ",{action:"complete-consent",disabled:true})}`;
    case "A-06": return `${authHead("เลือก role","ใช้ RMA Delivery ในโหมดไหน?","บัญชีเดียวสลับบทบาทได้ทุกเมื่อ")}${[["ลูกค้า","สั่งอาหาร · เรียกรถรับส่งคน","C-01","ใช้งานอยู่","success"],["ร้านค้า","รับออเดอร์ · จัดการเมนูและยอดขาย","M-03","ยังไม่ได้สมัคร · สมัครร้านค้า","warning"],["ไรเดอร์ / คนขับ","รับงานส่งอาหารและรับส่งคน","R-03","รออนุมัติเอกสาร","info"]].map((x)=>card(`<div class="row"><span class="state-illustration">${x[0]==="ลูกค้า"?'person':'business'}</span><span style="flex:1"><strong>${x[0]}</strong><small class="muted" style="display:block">${x[1]}</small>${badge(x[3],x[4])}</span>${x[0]==="ลูกค้า"?button("เข้าใช้งาน",{route:x[2],small:true}):button(x[3].includes("สมัคร")?"สมัคร":"ดูสถานะ",{route:x[3].includes("สมัคร")?"M-01":"R-02",variant:"secondary",small:true})}</div>`)).join("")}`;
    case "A-07": return `${authHead("05 / 06","เปิดใช้บริการใกล้ตัว","อนุญาตเฉพาะสิ่งที่จำเป็นต่อการใช้งาน")}${card(`<div class="row"><span class="state-illustration">⌖</span><div style="flex:1"><strong>ตำแหน่งที่ตั้ง</strong><div class="muted small">ใช้หาร้านใกล้คุณ คำนวณเส้นทาง และส่งถึงจุดหมาย</div></div></div>${button("อนุญาตตำแหน่งขณะใช้แอป",{action:"allow-location",variant:"secondary"})}<div class="row" style="margin-top:15px"><span class="state-illustration">▣</span><div><strong>การแจ้งเตือน</strong><div class="muted small">แจ้งสถานะ order และข้อความสำคัญ</div></div></div>${button("เปิดการแจ้งเตือน",{action:"allow-notifications",variant:"ghost"})}`)}${button("ไปหน้าหลัก",{route:"C-01"})}${button("ข้ามตอนนี้",{route:"C-01",variant:"ghost"})}`;
    default: return `${authHead("เริ่มต้น","เลือกโหมด","กลับไปเริ่มใช้งาน")}${button("ไปหน้าหลัก",{route:"C-01"})}`;
  }
}
