import { button, card, field, keyboardDemo, section, statePanel } from "./components.js";

export function renderShared(id,ctx) {
  const nav = ctx.nav(ctx.activeRole === "M" ? "M" : ctx.activeRole === "R" ? "R" : "C");
  if (id === "S-01") return `<div class="page-heading"><span class="eyebrow">SYSTEM COMPONENT · EMPTY</span><h2>ยังไม่มีรายการใหม่</h2><p>หน้าว่างควรบอกเหตุผลและบอกทางไปต่อ</p></div>${card(statePanel({icon:"▤",title:"ยังไม่มี order ใหม่",message:"ออเดอร์ที่เข้ามาจะแสดงตรงนี้ เมื่อร้านเปิดรับรายการ"}))}${section('ตัวอย่างตามบริบท',card(statePanel({icon:'♡',title:'ยังไม่มีร้านโปรด',message:'แตะรูปหัวใจที่ร้านเพื่อบันทึกร้านไว้'}))+card(statePanel({icon:'⌖',title:'ยังไม่มีประวัติการเดินทาง',message:'เรียกรถครั้งแรกและประวัติจะแสดงที่นี่'})))}${button('เปิดรายการอาหาร',{route:'C-04'})}${nav}`;
  if (id === "S-02") return `<div class="page-heading"><span class="eyebrow">SYSTEM COMPONENT · ERROR</span><h2>การเชื่อมต่อขัดข้อง</h2><p>เมื่อเน็ตหลุดให้บอกสถานะและมีปุ่มลองใหม่</p></div>${card(`<div class="state-box"><div><div class="state-illustration">⌁</div><strong>เชื่อมต่อเซิร์ฟเวอร์ไม่ได้</strong><p class="muted small">ตรวจสัญญาณอินเทอร์เน็ตแล้วลองอีกครั้ง รายการอาจยังไม่อัปเดต</p>${button('ลองอีกครั้ง',{action:'retry'})}</div></div>`)}${card(`<strong>หมายเลขอ้างอิง</strong><div class="muted small">NET-504 · ตัวอย่างหน้าข้อผิดพลาด</div><div class="muted micro">ข้อมูลเงินและสถานะจริงต้องมาจาก server เท่านั้น</div>`)}${nav}`;
  if (id === "S-03") return `<div class="page-heading"><span class="eyebrow">SYSTEM COMPONENT · SKELETON</span><h2>กำลังโหลดข้อมูล</h2><p>ใช้ skeleton ให้สัดส่วนใกล้เคียงเนื้อหาจริง</p></div>${section('รายการร้าน',`<div class="card"><div class="skeleton" style="height:126px"></div><div class="skeleton skeleton-line" style="width:62%"></div><div class="skeleton skeleton-line" style="width:88%"></div></div><div class="card"><div class="row"><div class="skeleton" style="height:64px;width:64px;border-radius:15px"></div><div style="flex:1"><div class="skeleton skeleton-line"></div><div class="skeleton skeleton-line" style="width:70%"></div></div></div></div>`)}${section('หน้าร้าน',`<div class="card"><div class="skeleton" style="height:145px"></div><div class="skeleton skeleton-line"></div><div class="skeleton skeleton-line" style="width:70%"></div></div>`)}${nav}`;
  if (id === "S-04") return `<div class="page-heading"><span class="eyebrow">SYSTEM COMPONENT · FEEDBACK</span><h2>ผลตอบสนองของหน้าจอ</h2><p>แสดง snackbar, dialog และ bottom sheet ในบริบท</p></div>${card(`<strong>Snackbar · ผลของการกระทำ</strong><p class="muted small">ใช้ข้อความสั้น ไม่ขวางการทำงานต่อ</p>${button('แสดง snackbar',{action:'toast-demo',variant:'secondary'})}`)}${card(`<strong>Dialog · ยืนยันการตัดสินใจ</strong><p class="muted small">ใช้เฉพาะกรณีสำคัญ เช่น ยกเลิกงาน</p>${button('เปิด dialog',{action:'dialog-demo',variant:'ghost'})}`)}${card(`<strong>Bottom sheet · ข้อมูลระหว่างรอ</strong><p class="muted small">รายละเอียด order / การชำระ / จุดแวะ</p>${button('เปิด bottom sheet',{action:'sheet-demo'})}`)}${nav}`;
  return `<div class="page-heading"><span class="eyebrow">SYSTEM COMPONENT · STATES</span><h2>ชุด component กลาง</h2><p>เปรียบเทียบสถานะปุ่มและช่องกรอกข้อมูล</p></div>${section('ปุ่ม',`<div class="stack">${button('ปุ่มหลัก · ปกติ',{action:'toast-demo'})}${button('ปุ่มรอง · secondary',{action:'toast-demo',variant:'secondary'})}${button('ปุ่มเส้นขอบ · ghost',{action:'toast-demo',variant:'ghost'})}<button class="btn pressed-demo" data-action="toast-demo">สถานะกำลังกด</button>${button('กำลังส่งข้อมูล…',{action:'toast-demo',disabled:true})}${button('ปิดใช้งาน',{action:'toast-demo',disabled:true,variant:'ghost'})}</div>`)}${card(`<strong>Input states</strong>${field('ปกติ','กรอกข้อมูล')}${field('มีค่า','พิมพ์ได้','text','ตัวอย่างข้อมูล')}<div class="form-field"><label>เบอร์โทรศัพท์ไม่ถูกต้อง</label><input class="field error" type="tel" value="0812345678" aria-invalid="true"/><small class="field-error">กรุณาตรวจสอบเบอร์โทรศัพท์ 10 หลัก</small></div><div class="form-field"><label>กำลังพิมพ์</label><input class="field focus-demo" value="ตัวอย่างช่องที่กำลัง focus"/></div>${keyboardDemo()}`)}${card(`<strong>สถานะ</strong><div class="row" style="flex-wrap:wrap;margin-top:10px"><span class="pill success">สำเร็จ</span><span class="pill warning">กำลังดำเนินการ</span><span class="pill danger">ผิดพลาด</span><span class="pill info">ข้อมูล</span></div>`)}`;
}
