import { ADDRESS, DESTINATION, ORDER_NO, PEOPLE, PICKUP, PHOTOS, VEHICLES } from "../data/content.js";
import { accountFooter, appBar, badge, button, card, field, iconButton, infoRows, section, segmented, sosButton, textArea } from "./components.js";
import { homeIcon } from "./home-icons.js";

const BACK = { "R-06": "R-05", "R-07": "R-06", "R-08": "R-07", "R-17": "R-16", "R-18": "R-05" };
const head = (id,title,sub="",trailing="") => appBar(title,{subtitle:sub,back:!['R-03','R-10','R-11','R-12','R-15'].includes(id),route:BACK[id]||'R-03',trailing});
const map = ({ full = false, pill = "ห้วยขวาง", nav = false } = {}) => `<div class="map-card ${full ? "map-full" : ""}"><div class="map-road" style="width:74%;top:35%;left:12%"></div><div class="map-road" style="width:60%;top:68%;left:24%;transform:rotate(20deg)"></div><div class="map-pin" style="top:25%;left:27%"><span>รับ</span></div><div class="map-pin" style="top:62%;left:69%;background:var(--accent)"><span>ส่ง</span></div><span class="pill" style="position:absolute;bottom:10px;left:10px">${pill}</span>${nav ? `<button class="icon-btn" data-action="toast-navigate" aria-label="นำทาง" title="นำทาง" style="position:absolute;right:12px;bottom:12px;width:56px;height:56px">${homeIcon("navigation", 28)}</button>` : ""}</div>`;
const addr = ADDRESS.split(",")[0];
const contactIcons = (chatRoute = "C-13") => `<div class="row">${iconButton("call", "โทร", 'data-action="toast-call"')}${iconButton("message", "แชท", `data-route="${chatRoute}"`)}</div>`;
const payBox = (cash, amount) => cash ? card(`<span class="eyebrow">ต้องเก็บเงินสดจากลูกค้า</span><strong style="font-size:34px">฿${amount}</strong>`, "tint") : `<div class="row-between"><span class="muted small">การชำระเงิน</span>${badge("ชำระออนไลน์แล้ว", "success")}</div>`;
export function renderRider(id,ctx) {
  switch(id) {
    case "R-01": return `${head(id,'สมัครเป็นไรเดอร์','เลือกประเภทงานที่ต้องการรับ')}${card(`<strong>ประเภทงาน</strong><div class="toggle-row"><span>ส่งอาหาร · มอเตอร์ไซค์</span><input type="checkbox" checked></div><div class="toggle-row"><span>รับส่งผู้โดยสาร · รถยนต์</span><input type="checkbox" checked></div><div class="muted micro">เลือกได้ตามประเภทรถและเอกสารที่สมัคร</div>`)}${card(`${field('ชื่อ-นามสกุล',PEOPLE.courier.name)}${field('เบอร์โทรศัพท์',PEOPLE.courier.phone,'tel')}${field('ทะเบียนรถ',PEOPLE.courier.plate)}${field('รุ่น / สีรถมอเตอร์ไซค์',PEOPLE.courier.bike)}${field('ทะเบียนรถยนต์',PEOPLE.courier.carPlate)}${field('รุ่น / สีรถยนต์',PEOPLE.courier.car)}<strong class="small">เอกสารตัวอย่าง</strong>${['บัตรประชาชน','ใบขับขี่','ทะเบียนรถ','บัญชีรับเงิน'].map(x=>`<div class="toggle-row"><span>${x}</span><button class="btn inline secondary" data-action="toast-upload">แนบ</button></div>`).join('')}`)}${button('ส่งใบสมัคร',{route:'R-02'})}`;
    case "R-02": {const bad=ctx.state==='เอกสารถูกตีกลับ'; return `${head(id,bad?'ต้องแก้เอกสาร':'สถานะการสมัคร','สมัครเมื่อ 7 ต.ค. 2569 · หมายเลข R-20841')}${card(`<div class="state-illustration">${bad?'!':'◷'}</div><strong>${bad?'ใบขับขี่หมดอายุ / ภาพไม่ชัด':'กำลังตรวจสอบเอกสารคนขับ'}</strong><p class="muted small">${bad?'อัปโหลดใบขับขี่ฉบับปัจจุบันและถ่ายภาพใหม่ให้เห็นข้อมูลครบถ้วน':'ทีมงานกำลังตรวจเอกสารและข้อมูลรถ ใช้เวลาโดยประมาณ 1–2 วันทำการ'}</p>${badge(bad?'ต้องแก้ไข':'กำลังตรวจ','warning')}`)}${card(`<strong>รายการเอกสาร</strong>${infoRows([["บัตรประชาชน","ตรวจแล้ว","success"],["ใบขับขี่",bad?'ถูกตีกลับ':'รอตรวจ',bad?'danger':'warning'],["ทะเบียนรถ","ผ่าน","success"],["บัญชีรับเงิน","รอตรวจ","warning"]])}`)}${button(bad?'ส่งเอกสารใหม่':'ดูข้อมูลสมัคร',{action:bad?'toast-upload':'toast-application'})}`; }
    case "R-03": return `${head(id,'พร้อมออกไปทำงานไหม?',PEOPLE.courier.name)}${card(`<div class="row-between"><div><strong>${ctx.riderOnline?'ออนไลน์แล้ว':'ออฟไลน์'}</strong><div class="muted small">${ctx.riderOnline?'กำลังรับงานในพื้นที่ห้วยขวาง':'เปิดรับงานเมื่อพร้อมออกเดินทาง'}</div></div><button class="switch ${ctx.riderOnline?'on':''}" data-action="rider-online"></button></div>`)}${map()}${card(`<strong>ประเภทงานที่รับ</strong><div class="form-field"><label for="work-type-select">เลือกประเภทที่พร้อมรับตอนนี้</label><select id="work-type-select" class="select" data-task-type><option value="food" ${ctx.taskType==="food"?"selected":""}>ส่งอาหาร · มอเตอร์ไซค์</option><option value="passenger" ${ctx.taskType==="passenger"?"selected":""}>รับส่งคน · รถยนต์</option></select><div class="muted micro">รับงานได้ครั้งละ 1 ประเภท · ระหว่างรับส่งคนจะไม่มีงานอื่นเข้า · ระหว่างส่งอาหารอาจมีงานพ่วง</div></div>`)}<div class="metric-grid"><div class="metric"><span>รายได้วันนี้</span><strong>฿1,248</strong></div><div class="metric"><span>งานสำเร็จ</span><strong>12</strong></div></div>${ctx.riderOnline?button('ดูงานตัวอย่าง',{route:'R-04'}):button('เปิดออนไลน์เพื่อรับงาน',{action:'rider-online',variant:'secondary'})}${ctx.nav('R')}`;
    case "R-04": {
      const kind = ["food", "passenger", "bundle"].includes(ctx.offerKind) ? ctx.offerKind : "food";
      const O = {
        food: { title: "งานส่งอาหารใหม่", pill: "ส่งอาหาร · มอเตอร์ไซค์", money: "฿52", note: "+ ทิป", dist: "3.8 กม. · 14 นาที", rows: [["รับที่", PICKUP], ["ส่งที่", addr], ["ระยะถึงจุดรับ", "2.1 กม. · 8 นาที"]], note2: "ตรวจจุดรับและจุดส่งก่อนกดรับงาน เมื่อรับแล้วการยกเลิกอาจมีผลต่ออัตรารับงานของคุณ", go: "R-05" },
        passenger: { title: "งานรับส่งคนใหม่", pill: "รับส่งคน · รถยนต์", money: "฿86", note: "ค่าโดยสาร", dist: "8.4 กม. · 24 นาที", rows: [["จุดรับ", addr], ["ปลายทาง", "อโศก ทาวเวอร์ ถนนสุขุมวิท 21"], ["ประเภทรถ", "รถยนต์ประหยัด · 4 ที่นั่ง"], ["ระยะถึงจุดรับ", "1.1 กม. · 4 นาที"]], note2: "ระหว่างรับส่งคนจะไม่มีงานอาหารหรืองานพ่วงเข้า จนกว่าจะส่งผู้โดยสารถึงปลายทาง", go: "R-16" },
        bundle: { title: "งานพ่วงเพิ่ม", pill: "งานพ่วง · ระหว่างส่งอาหาร", money: "+฿18", note: "ค่าตอบแทนที่เพิ่ม", dist: "เพิ่ม 1.4 กม. · +8 นาที", rows: [["รับเพิ่มที่", "บ้านขนมไทยคุณยาย"], ["ส่งเพิ่มที่", "88/5 ซอยรัชดาภิเษก 12"], ["งานปัจจุบัน", `${ORDER_NO} ส่งต่อตามเดิม`], ["ลูกค้างานพ่วง", "คุณธีรภัทร"]], note2: "งานพ่วงอยู่ในเส้นทางเดิม ลูกค้าออเดอร์หลักจะได้รับแจ้งว่ามีจุดแวะเพิ่มและเวลาถึงที่ปรับแล้ว", go: "R-18" }
      }[kind];
      return `${appBar(O.title, { subtitle: "รับหรือปฏิเสธภายในเวลาที่กำหนด", back: false })}<div class="state-box" style="min-height:130px"><div><div class="offer-countdown" style="width:104px;height:104px;font-size:26px;margin:0 auto" role="timer" data-live-countdown="28" data-expire-go="R-03" data-expire-msg="หมดเวลารับงาน งานถูกส่งต่อให้ไรเดอร์คนอื่น">00:28</div></div></div><div style="text-align:center"><span class="pill ${kind === "bundle" ? "info" : "brand"}">${O.pill}</span><div style="margin-top:8px"><strong style="font-size:40px">${O.money}</strong> <span class="muted small">${O.note}</span></div><div class="muted small">${O.dist}</div></div>${card(infoRows(O.rows))}<div class="muted small" style="padding:0 4px">${O.note2}</div><div class="sticky-action">${button("รับงาน", { route: O.go })}<button class="text-btn" style="display:block;margin:8px auto 0" data-action="decline-offer">ปฏิเสธงาน</button></div>`;
    }
    case "R-05": return `${head(id, "ไปรับอาหาร", `งาน ${ORDER_NO}`, sosButton())}${map({ full: true, nav: true })}${card(`<div class="row-between"><span class="pill brand">ไปรับที่ร้าน</span>${badge("อีก 8 นาที", "warning")}</div><div class="row-between"><div><h3 style="margin:8px 0 2px">${PEOPLE.merchant.name}</h3><div class="muted small">${PICKUP}</div></div>${contactIcons()}</div>${infoRows([["ระยะทางถึงร้าน", "2.1 กม. · 8 นาที"], ["ค่าตอบแทน", "฿52 + ทิป"]])}`)}${card(`<div class="row-between"><div class="row"><span class="avatar">${PEOPLE.customer.initials}</span><div><strong class="small">ผู้รับ ${PEOPLE.customer.name}</strong><div class="muted micro">ส่งที่ ${addr}</div></div></div>${contactIcons()}</div>`)}<div class="sticky-action">${button("ถึงร้านแล้ว", { route: "R-06" })}</div>`;
    case "R-06": return `${head(id,'ตรวจสอบก่อนรับอาหาร','ยืนยัน order ให้ตรงก่อนออกจากร้าน')}${card(`<div class="row-between"><span class="pill brand">${ORDER_NO}</span>${badge('รอรับอาหาร','warning')}</div><div class="muted small">${PEOPLE.merchant.name} · ${PICKUP}</div><hr style="border:0;border-top:1px solid var(--line)">${ctx.orderItems.map(item=>`<div class="info-row"><span>${item.name}</span><strong>${item.qty} ${item.qty>1?"รายการ":"กล่อง"}</strong></div>`).join('')}<div class="info-row"><span>หมายเหตุ</span><strong>ไม่ใส่ผักชี</strong></div><div class="row-between">${button('＋ ถ่ายรูปสภาพอาหาร',{action:'toast-camera',variant:'secondary',small:true})}${badge('ถ่ายภาพจำลอง','info')}</div>`)}${card(`<strong>ข้อควรตรวจ</strong><div class="muted small">ตรวจเลข order · จำนวนถุง · เครื่องดื่มแยกถุงก่อนยืนยันรับ</div>`)}${button('ยืนยันรับอาหารแล้ว',{route:'R-07'})}`;
    case "R-07": return `${head(id,'นำส่งให้ลูกค้า','กำลังเดินทางไปยังจุดส่ง')}${map()}${card(`<div class="row-between"><span class="pill success">รับอาหารแล้ว</span><strong>ถึงใน 14 นาที</strong></div><div class="muted small" style="margin-top:8px">${ADDRESS}</div><div class="muted micro">กรุณาวางที่ล็อบบี้ หากลูกค้าไม่รับสายรอ 3 นาที</div>${infoRows([["คำสั่งซื้อ",ORDER_NO],["ระยะทาง","3.8 กม."],["เงินสดที่ต้องเก็บ","฿0 · ชำระออนไลน์"]])}<div class="row-between">${button('นำทาง',{action:'toast-navigate',variant:'secondary',small:true})}${button('โทรลูกค้า',{action:'toast-call',variant:'ghost',small:true})}</div>`)}${card(`${textArea('หมายเหตุถึงผู้รับ','ประตูอยู่ด้านข้างอาคาร')}`)}${button('ถึงจุดส่งแล้ว',{route:'R-08'})}${button('ดูจุดแวะทั้งหมด',{route:'R-18',variant:'ghost'})}`;
    case "R-08": {
      const cash = Boolean(ctx.orderCash);
      const amount = ctx.subtotal + 15 - (ctx.discount || 0);
      const proof = Boolean(ctx.proofTaken);
      const ready = proof && (!cash || ctx.cashCollected);
      return `${head(id, "ยืนยันส่งสำเร็จ", "ถ่ายรูปหลักฐานก่อนปิดงาน")}${card(`<div class="state-box" style="min-height:150px"><div><div class="state-illustration">${homeIcon(proof ? "checkCircle" : "camera", 30)}</div><strong>${proof ? "บันทึกรูปหลักฐานแล้ว" : "ถ่ายรูปหลักฐานการส่ง"}</strong><p class="muted small">${proof ? "ตรวจดูรูปแล้วกดยืนยันได้" : "เช่น วางอาหารที่ล็อบบี้ หรือส่งให้ผู้รับโดยตรง · จำเป็นต้องมีก่อนปิดงาน"}</p>${button(proof ? "ถ่ายรูปใหม่" : "เปิดกล้อง", { action: "take-proof", variant: "secondary" })}</div></div>`)}${cash ? payBox(true, amount) : ""}${cash ? `<button class="toggle-row ${ctx.cashCollected ? "selected" : ""}" data-action="cash-collected" aria-pressed="${Boolean(ctx.cashCollected)}"><span>รับเงินสดครบ ฿${amount} แล้ว</span><span>${ctx.cashCollected ? homeIcon("check", 18) : ""}</span></button>` : card(`${payBox(false, amount)}<div class="row-between"><span>ค่าตอบแทนงานนี้</span><strong>฿52 + ทิป</strong></div>`)}<button class="text-btn" data-action="cannot-reach">ติดต่อลูกค้าไม่ได้</button><div class="sticky-action">${button("ยืนยันส่งอาหารแล้ว", { route: "R-09", disabled: !ready })}${!ready ? `<div class="muted micro" style="margin-top:6px">${!proof ? "ถ่ายรูปหลักฐานก่อนยืนยัน" : "ยืนยันว่ารับเงินสดครบก่อนปิดงาน"}</div>` : ""}</div>`;
    }
    case "R-09": return `${head(id,ctx.taskType==='passenger'?'สรุปเที่ยว':'สรุปงาน',ctx.taskType==='passenger'?'รับส่งคน · RM-RIDE-261007-63':`ส่งสำเร็จ · ${ORDER_NO}`)}${card(`<div class="state-illustration">✓</div><strong>${ctx.taskType==='passenger'?'ส่งผู้โดยสารถึงปลายทาง':'ส่งอาหารให้ลูกค้าเรียบร้อย'}</strong><div class="muted small">${ctx.taskType==='passenger'?'นพดล พรหมรักษ์':PEOPLE.customer.name} · 12:47 น.</div><div class="price-line total"><span>รายได้จากงานนี้</span><strong>${ctx.taskType==='passenger'?'฿86':'฿52'}</strong></div><div class="row-between"><span>ทิปจากลูกค้า</span><strong>฿20</strong></div>`,'tint')}${card(infoRows([["เวลารวม","28 นาที"],["ระยะทาง","5.9 กม."],["คะแนนลูกค้า","5.0 ★"]]))}${button('ดูงานถัดไป',{route:'R-03'})}${button('ดูประวัติงาน',{route:'R-10',variant:'ghost'})}`;
    case "R-10": return `${head(id,'ประวัติงาน','สรุปงานที่ทำสำเร็จและถูกยกเลิก')}${divTabs()}${[["อาหาร",ORDER_NO,"ครัวบ้านสวน → ห้วยขวาง","฿72","12:47"],["รับส่งคน","RM-RIDE-261007-63","ห้วยขวาง → อโศก","฿64","11:20"],["อาหาร","RM-261007-1728","ร้านข้าวมันไก่ → รัชดา","฿48","10:58"]].map(x=>card(`<div class="row-between"><span class="pill brand">${x[0]}</span><strong>${x[3]}</strong></div><div class="small">${x[2]}</div><div class="row-between muted micro"><span>${x[1]}</span><span>วันนี้ ${x[4]}</span></div>`)).join('')}${ctx.nav('R')}`;
    case "R-11": return `${head(id,'รายได้และกระเป๋า','ยอดโอนรอบถัดไป ศุกร์ 9 ต.ค.')}${card(`<span class="eyebrow">รายได้ที่ถอนได้</span><strong style="font-size:30px">฿4,285.50</strong><div class="muted small">รวมรายได้ 7–13 ต.ค. 2569</div>${button('ถอนเงินเข้าบัญชี',{action:'withdraw',variant:'secondary'})}`,'tint')}${card(`<strong>เงินสดที่ต้องนำส่ง</strong><div class="row-between"><strong>฿320</strong>${badge('นำส่งภายในวันนี้','warning')}</div><div class="muted micro">ยอดเงินสดที่รับจากลูกค้า</div>`)}${section('รายการล่าสุด',[['ส่งอาหาร','฿52','12:47'],['รับส่งคน','฿64','11:20'],['โบนัสช่วงเร่งด่วน','฿35','10:00']].map(x=>card(`<div class="row-between"><span>${x[0]}</span><strong>${x[1]}</strong></div><div class="muted micro">วันนี้ ${x[2]} น.</div>`)).join(''))}${ctx.nav('R')}`;
    case "R-12": return `${head(id,'รายงานผลงาน','สรุปสัปดาห์ 1–7 ต.ค.')}${card(`<div class="row-between"><span>รายได้รวม</span>${badge('↑ 8%','success')}</div><strong style="font-size:28px">฿6,840</strong><div class="muted small">จากงานสำเร็จ 68 งาน</div><div class="chart">${[44,63,52,70,58,92,74].map((v,i)=>`<div class="chart-bar" style="height:${v}%"><small>${i+1}</small></div>`).join('')}</div>`)}<div class="metric-grid"><div class="metric"><span>อัตรารับงาน</span><strong>92%</strong></div><div class="metric"><span>คะแนนเฉลี่ย</span><strong>4.92 ★</strong></div><div class="metric"><span>ตรงเวลา</span><strong>96%</strong></div><div class="metric"><span>Incentive</span><strong>฿480</strong></div></div>${ctx.nav('R')}`;
    case "R-13": return `${head(id,'ข้อมูลส่วนตัวและรถ','จัดการเอกสารก่อนหมดอายุ')}${card(`<div class="row"><span class="avatar large">${PEOPLE.courier.initials}</span><div><strong>${PEOPLE.courier.name}</strong><div class="muted small">${PEOPLE.courier.phone}</div></div></div>`)}${card(`<strong>รถที่ลงทะเบียน</strong>${infoRows([["ประเภทรถ","มอเตอร์ไซค์ + รถยนต์"],["มอเตอร์ไซค์",`${PEOPLE.courier.bike} · ${PEOPLE.courier.plate}`],["รถยนต์",`${PEOPLE.courier.car} · ${PEOPLE.courier.carPlate}`]])}<button class="text-btn" data-action="edit-vehicle">แก้ไขข้อมูลรถ</button>`)}${card(`<strong>เอกสาร</strong>${infoRows([["บัตรประชาชน","ผ่าน · หมดอายุ 2572","success"],["ใบขับขี่","หมดอายุ 20 พ.ย. 2569","warning"],["ทะเบียนรถ","ผ่าน","success"]])}<button class="btn secondary" data-action="toast-upload">อัปเดตเอกสาร</button>`)}${ctx.nav('R')}`;
    case "R-14": return `${head(id,'ช่วยเหลือและฉุกเฉิน','ติดต่อเจ้าหน้าที่ได้ตลอด 24 ชม.')}${card(`<div class="row"><span class="state-illustration">!</span><div><strong>แจ้งเหตุฉุกเฉิน</strong><div class="muted small">อุบัติเหตุ · ไม่ปลอดภัย · ต้องการความช่วยเหลือ</div></div></div>${button('โทรสายด่วน 1669',{action:'emergency',variant:'danger'})}`)}${section('ปัญหาเกี่ยวกับงาน',['รายงานลูกค้าไม่รับสาย','ปัญหาที่ร้านค้า','ชำระเงินไม่ตรง','แจ้งเหตุระหว่างทาง'].map(x=>card(`<div class="row-between"><span class="small">${x}</span><button class="text-btn" data-action="toast-support">แจ้งปัญหา</button></div>`)).join(''))}${button('แชทเจ้าหน้าที่',{action:'toast-support',variant:'secondary'})}`;
    case "R-15": {
      const linkRow = (route, label) => `<button class="row-between card" style="width:100%;text-align:left" data-route="${route}"><span>${label}</span>${homeIcon("chevron", 18)}</button>`;
      return `${head(id, "บัญชีไรเดอร์", "จัดการข้อมูลและตั้งค่า")}${card(`<div class="row"><span class="avatar large">${PEOPLE.courier.initials}</span><div><strong>${PEOPLE.courier.name}</strong><div class="muted micro">★ 4.92 · สถานะเอกสารครบ</div></div></div>`, "tint")}${section("บัญชี", [["R-13", "ข้อมูลส่วนตัวและรถ"], ["R-11", "รายได้และกระเป๋า"], ["R-14", "ศูนย์ช่วยเหลือ / ฉุกเฉิน"]].map((x) => linkRow(x[0], x[1])).join(""))}${section("ตั้งค่า", card(`<div class="toggle-row"><span>เสียงแจ้งงานใหม่</span><button class="switch ${ctx.soundOn === false ? "" : "on"}" data-action="toggle-sound" aria-label="เสียงแจ้งงานใหม่" aria-pressed="${ctx.soundOn !== false}"></button></div><strong class="small">ภาษา</strong>${segmented([["th", "ไทย"], ["en", "English"]], ctx.appLang || "th", "set-lang")}<strong class="small">ธีม</strong>${segmented([["light", "สว่าง"], ["dark", "มืด"], ["system", "ตามระบบ"]], ctx.themePreference || "light", "set-theme")}`))}${card(`<strong class="small">เปลี่ยนโหมดการใช้งาน</strong><div class="muted micro">ใช้บัญชีเดียวกันกับลูกค้าและร้านค้า</div>${button("สลับ role", { route: "A-06", variant: "secondary" })}`)}${accountFooter()}${ctx.nav("R")}`;
    }
    case "R-16": {
      const step = Number(ctx.rideStep || 0);
      const cash = ctx.ridePayment === "เงินสด";
      return `${head(id, step ? "รอผู้โดยสารขึ้นรถ" : "ไปรับผู้โดยสาร", "งานรับส่งคน · รถยนต์ประหยัด", sosButton())}${map({ full: true, nav: true })}${card(`<div class="row-between"><span class="pill brand">จุดรับผู้โดยสาร</span>${badge(step ? "ถึงจุดรับแล้ว" : "อีก 4 นาที", "warning")}</div><div class="row-between"><div class="row"><span class="avatar">นพ</span><div><strong>นพดล พรหมรักษ์</strong><div class="muted small">ผู้โดยสาร 1 คน</div></div></div>${contactIcons()}</div><div class="muted small" style="margin-top:8px">รับที่ ${addr}</div><div class="muted micro">จุดสังเกต: หน้าอาคารฝั่งถนนใหญ่</div>`)}${card(`<div class="row-between"><strong>ปลายทาง</strong><span>อโศก ทาวเวอร์ · 8.4 กม.</span></div><div class="row-between"><span class="muted small">ค่าโดยสาร ฿86</span>${badge(cash ? "เก็บเงินสด" : "ชำระออนไลน์", cash ? "warning" : "success")}</div>`)}${step ? "" : `<button class="text-btn" data-action="passenger-no-show">ผู้โดยสารไม่มา</button>`}<div class="sticky-action">${step ? button("เริ่มเดินทาง", { action: "ride-start" }) : button("ถึงจุดรับแล้ว", { action: "ride-arrived" })}</div>`;
    }
    case "R-17": {
      const cash = ctx.ridePayment === "เงินสด";
      return `${head(id, "นำส่งผู้โดยสาร", "ห้ามรับงานอื่นระหว่างเที่ยว", sosButton())}${map({ full: true, nav: true })}${card(`<div class="row-between"><span class="pill success">ผู้โดยสารขึ้นรถแล้ว</span>${badge("ถึงใน 24 นาที", "info")}</div><div class="muted small">ปลายทาง · อโศก ทาวเวอร์ ถนนสุขุมวิท 21</div>${infoRows([["ผู้โดยสาร", "นพดล พรหมรักษ์"], ["ระยะทาง", "8.4 กม."], ["ค่าโดยสารประเมิน", "฿86"], ["วิธีชำระ", cash ? "เงินสด" : "พร้อมเพย์"]])}<div class="muted small">ช่วงรับส่งคนจะไม่มีงานอาหารหรืองานพ่วงเข้า · กดถึงปลายทางเมื่อผู้โดยสารลงรถแล้วเท่านั้น</div>`)}${cash ? payBox(true, 86) : ""}<div class="sticky-action">${button("ถึงปลายทางแล้ว", { route: "R-09" })}</div>`;
    }
    case "R-18": {
      const stops = [
        { kind: "รับ", title: "รับออเดอร์หลัก", place: PEOPLE.merchant.name, address: PICKUP, order: ORDER_NO, current: true },
        { kind: "รับ", title: "รับออเดอร์พ่วง", place: "บ้านขนมไทยคุณยาย", address: "55/3 ซอยประชาราษฎร์บำเพ็ญ 4", order: "RM-261007-1851" },
        { kind: "ส่ง", title: "ส่งออเดอร์พ่วง", place: "คุณธีรภัทร", address: "88/5 ซอยรัชดาภิเษก 12", order: "RM-261007-1851" },
        { kind: "ส่ง", title: "ส่งออเดอร์หลัก", place: PEOPLE.customer.short, address: addr, order: ORDER_NO }
      ];
      return `${head(id, "ลำดับจุดแวะ", "งานอาหารพ่วง · รวม 2 ออเดอร์")}${card(`<div class="row-between"><strong>เส้นทางแนะนำ</strong>${badge("เพิ่ม 1.4 กม. · +8 นาที", "info")}</div><div class="muted small">ค่าตอบแทนงานพ่วงเพิ่ม ฿18</div>`, "tint")}<div class="step-list">${stops.map((x, i) => `<div class="step ${x.current ? "current" : ""}"><span class="step-dot">${i + 1}</span><div class="step-copy"><div class="row-between"><span class="pill ${x.kind === "รับ" ? "brand" : "success"}">${x.kind}</span>${x.current ? badge("จุดถัดไป", "warning") : ""}</div><strong>${x.title}</strong><small>${x.place} · ${x.address}</small><small>${x.order}</small></div>${iconButton("navigation", `นำทางไป${x.title}`, 'data-action="toast-navigate"')}</div>`).join("")}</div>${card(`<strong>เวลาที่ลูกค้าเห็น</strong><div class="muted small">ลูกค้าออเดอร์หลักได้รับแจ้งว่ามีจุดแวะเพิ่ม และเห็นเวลาถึงที่ปรับแล้ว</div>`)}<div class="sticky-action">${button("ยืนยันเส้นทางและไปรับ", { route: "R-06" })}<button class="text-btn" style="display:block;margin:8px auto 0" data-route="R-05">กลับงานปัจจุบัน</button></div>`;
    }
    default: return `${head(id,'งานของฉัน',PEOPLE.courier.name)}${card(infoRows([["งานวันนี้","12 งาน"],["รายได้","฿1,248"],["คะแนน","4.92 ★"],["สถานะ","ออนไลน์"]]))}${button('กลับหน้าไรเดอร์',{route:'R-03'})}`;
  }
}

function divTabs(){return `<div class="chip-list"><button class="chip active">ทั้งหมด</button><button class="chip">อาหาร</button><button class="chip">รับส่งคน</button><button class="chip">ยกเลิก</button></div>`;}
