import { ADDRESS, MENU, ORDER_NO, PEOPLE, PHOTOS } from "../data/content.js";
import { accountFooter, block, listGroup, listRow, profileRow, roleSwitchRow, settingsGroup, appBar, badge, button, card, field, infoRows, keyboardDemo, section, segmented, textArea } from "./components.js";
import { homeIcon } from "./home-icons.js";

const head = (id, title, sub="") => appBar(title,{subtitle:sub,back:!['M-03','M-06','M-13','M-16','M-17'].includes(id),route:'M-03'});
const chart = (values=[36,55,44,79,61,95,72]) => `<div class="chart">${values.map((v,i)=>`<div class="chart-bar" style="height:${v}%"><small>${['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.'][i]}</small></div>`).join('')}</div>`;
const ORDER_TABS = ["ใหม่", "กำลังทำ", "พร้อมส่ง", "เสร็จแล้ว"];
const orderList = (ctx) => [
  { no: ORDER_NO, who: PEOPLE.customer.short, total: ctx.subtotal, status: "ใหม่", timer: "รับภายใน 0:45 · เตรียมประมาณ 20 นาที", route: "M-04" },
  { no: "RM-261007-1851", who: "คุณธีรภัทร", total: 186, status: "ใหม่", timer: "รับภายใน 0:32 · เตรียมประมาณ 15 นาที", route: "M-04" },
  { no: "RM-261007-1829", who: "คุณมินตรา", total: 243, status: "กำลังทำ", timer: "ทำมาแล้ว 6 นาที · เหลือ 12 นาที", route: "M-05" },
  { no: "RM-261007-1815", who: "คุณปวีณ์", total: 129, status: "กำลังทำ", timer: "ทำมาแล้ว 14 นาที · เหลือ 4 นาที", route: "M-05" },
  { no: "RM-261007-1802", who: "คุณอริษา", total: 215, status: "พร้อมส่ง", timer: "รอไรเดอร์ถึงใน 5 นาที", route: "M-05" },
  { no: "RM-261007-1790", who: "คุณวีระ", total: 158, status: "เสร็จแล้ว", timer: "ส่งมอบ 12:02 น.", route: "M-05" },
  { no: "RM-261007-1776", who: "คุณนภา", total: 97, status: "เสร็จแล้ว", timer: "ส่งมอบ 11:41 น.", route: "M-05" }
];
const orderCard = (o) => `<button class="card order-sample" style="width:100%;text-align:left" data-route="${o.route}"><div class="row-between"><span class="pill brand">#${o.no}</span>${badge(o.status, o.status === "ใหม่" ? "warning" : o.status === "เสร็จแล้ว" ? "" : "success")}</div><div class="row-between" style="margin:8px 0"><strong>${o.who}</strong><strong>฿${o.total}</strong></div><div class="row-between"><span class="pill info">${homeIcon("clock", 14)} ${o.timer}</span>${homeIcon("chevron", 18)}</div></button>`;

export function renderMerchant(id, ctx) {
  switch(id) {
    case "M-01": return `${head(id,"สมัครร้านค้า","ขั้นตอน 1 จาก 3 · ข้อมูลร้าน")}${card(`<div class="step-list"><div class="step done"><span class="step-dot">✓</span><div class="step-copy"><strong>ข้อมูลร้าน</strong><small>กรอกชื่อและที่อยู่ร้าน</small></div></div><div class="step"><span class="step-dot">2</span><div class="step-copy"><strong>เอกสารร้าน</strong><small>ยืนยันตัวตนและใบอนุญาต (ตัวอย่าง)</small></div></div><div class="step"><span class="step-dot">3</span><div class="step-copy"><strong>บัญชีรับเงิน</strong><small>ตรวจชื่อบัญชีให้ตรงกับผู้สมัคร</small></div></div></div>${field('ชื่อร้าน','เช่น ครัวบ้านสวน รัชดา','text',PEOPLE.merchant.name)}${field('ชื่อผู้ติดต่อ','ชื่อ-นามสกุล','text',PEOPLE.merchant.owner)}${field('เบอร์โทรศัพท์ร้าน',PEOPLE.merchant.phone,'tel')}${field('ที่อยู่ร้าน','เลขที่ ซอย แขวง เขต จังหวัด','text',ADDRESS.split(',')[0])}${button('＋ แนบเอกสารร้านค้า',{action:'toast-upload',variant:'secondary'})}`)}${button('ดำเนินการต่อ · เอกสาร',{action:'toast-next-step'})}`;
    case "M-02": { const rejected=ctx.state==='เอกสารถูกตีกลับ'; const approved=ctx.state==='อนุมัติแล้ว'; return `${head(id,rejected?'ต้องแก้ไขเอกสาร':approved?'อนุมัติแล้ว':'ตรวจสอบข้อมูลร้าน','สมัครเมื่อ 7 ต.ค. 2569 · หมายเลข M-10482')}${card(`<div class="state-illustration">${rejected?'!':approved?'✓':'◷'}</div><strong>${rejected?'เอกสารบัญชีรับเงินไม่ชัดเจน':approved?'อนุมัติร้านค้าแล้ว':'กำลังตรวจสอบใบสมัคร'}</strong><p class="muted small">${rejected?'โปรดส่งภาพสมุดบัญชีหน้าแรกใหม่ ให้เห็นชื่อบัญชีและเลขบัญชีครบถ้วน':approved?'ร้านพร้อมเปิดใช้งาน · ตั้งค่าร้านและบัญชีรับเงินได้':'ทีมงานกำลังตรวจเอกสารและข้อมูลร้าน โดยปกติใช้เวลา 1–2 วันทำการ'}</p>${badge(rejected?'ต้องแก้ไข':approved?'อนุมัติแล้ว':'รอตรวจสอบ',rejected?'danger':approved?'success':'warning')}`)}${card(`<strong class="small">สถานะเอกสาร</strong>${infoRows([["หนังสือรับรองร้าน","ผ่าน","success"],["บัตรประชาชนผู้สมัคร",rejected?"ภาพไม่ชัด":"กำลังตรวจ","warning"],["บัญชีรับเงิน",rejected?"ต้องส่งใหม่":"รอตรวจ","warning"]])}`)}${button(rejected?'อัปโหลดเอกสารใหม่':'ดูข้อมูลใบสมัคร',{action:rejected?'toast-upload':'toast-application',variant:rejected?'':'secondary'})}${button('กลับหน้า order',{route:'M-03',variant:'ghost'})}`; }
    case "M-03": {
      const tab = ctx.orderTab || "ใหม่";
      const all = orderList(ctx);
      const shown = all.filter((o) => o.status === tab);
      const closed = ctx.merchantOpen === false;
      return `${head(id, "จัดการออเดอร์", PEOPLE.merchant.name)}${card(`<div class="row-between"><div><strong>${closed ? "ร้านปิดรับออเดอร์" : "ร้านเปิดรับออเดอร์"}</strong><div class="muted micro">${closed ? "ลูกค้าสั่งร้านนี้ไม่ได้ในตอนนี้" : "วันนี้ · อังคาร 7 ต.ค. 2569"}</div></div><button class="switch ${closed ? "" : "on"}" data-action="merchant-open" aria-label="เปิดหรือปิดรับออเดอร์" aria-pressed="${!closed}"></button></div><div style="margin-top:8px">${badge("เชื่อม Smart Kitchen", "success")}</div>`)}${closed ? card(`<strong>ร้านปิดรับออเดอร์ชั่วคราว</strong><p class="muted small">ออเดอร์ที่รับไว้แล้วยังต้องทำต่อ กดเปิดเมื่อพร้อมรับออเดอร์ใหม่</p>${button("เปิดรับออเดอร์", { action: "merchant-open" })}`) : ""}<div class="chip-list" role="tablist">${ORDER_TABS.map((t) => { const n = all.filter((o) => o.status === t).length; return `<button class="chip ${t === tab ? "active" : ""}" role="tab" aria-selected="${t === tab}" data-action="m-order-tab" data-value="${t}">${t} ${n}</button>`; }).join("")}</div>${shown.length ? shown.map(orderCard).join("") : card(`<strong>ไม่มีออเดอร์ในสถานะนี้</strong>`)}<button class="card" style="width:100%;text-align:left" data-route="M-13"><div class="row-between"><strong>สรุปวันนี้</strong>${homeIcon("chevron", 18)}</div><div class="metric-grid" style="margin-top:10px"><div class="metric"><span>ยอดขายสุทธิ</span><strong>฿8,420</strong></div><div class="metric"><span>ออเดอร์</span><strong>27</strong></div></div><div class="muted micro" style="margin-top:6px">แตะเพื่อดูรายงานเต็ม</div></button>${ctx.nav("M")}`;
    }
    case "M-04": return `${head(id,'ออเดอร์ใหม่เข้าแล้ว','เสียงแจ้งเตือน · รับภายใน 45 วินาที')}<div class="state-box" style="min-height:100px"><div class="offer-countdown">00:45</div></div>${card(`<div class="row-between"><span class="pill brand">#${ORDER_NO}</span>${badge('รับใหม่','warning')}</div><div class="row-between" style="margin:10px 0"><strong>${PEOPLE.customer.name}</strong><strong>฿${ctx.subtotal}</strong></div><div class="info-list">${ctx.orderItems.map(item=>`<div class="info-row"><span>${item.name}</span><strong>฿${item.price} × ${item.qty}</strong></div>`).join('')}<div class="info-row"><span>หมายเหตุ</span><strong>ไม่ใส่ผักชี</strong></div></div><div class="row-between" style="margin-top:10px"><span>เตรียมอาหาร</span><select class="select" style="width:115px"><option>20 นาที</option><option>25 นาที</option><option>30 นาที</option></select></div><div class="muted micro" style="margin-top:8px">ไรเดอร์ธนกรจะถึงร้านในประมาณ 8 นาที</div>`)}<div class="btn-row">${button('ปฏิเสธ',{action:'merchant-decline',variant:'ghost'})}${button('รับออเดอร์',{route:'M-05'})}</div>`;
    case "M-05": return `${head(id,'รายละเอียดออเดอร์','#'+ORDER_NO)}${card(`<div class="row-between"><strong>${PEOPLE.customer.name}</strong>${badge(ctx.merchantStatus||'กำลังทำ','warning')}</div><div class="muted small">${PEOPLE.customer.phone} · สั่ง 12:18 น.</div><hr style="border:0;border-top:1px solid var(--line)">${ctx.orderItems.map(item=>`<div class="info-row"><span>${item.name} × ${item.qty}</span><strong>฿${item.price*item.qty}</strong></div>`).join('')}<div class="price-line total"><span>ยอดค่าอาหาร</span><strong>฿${ctx.subtotal}</strong></div><div class="pill info">หมายเหตุ: ไม่ใส่ผักชี · แยกน้ำชา</div>`)}${card(`<div class="row"><span class="avatar">${PEOPLE.courier.initials}</span><div><strong>${PEOPLE.courier.name}</strong><div class="muted small">ไรเดอร์ · ${PEOPLE.courier.bike}</div></div><button class="btn inline secondary" data-action="toast-call">โทร</button><button class="btn inline ghost" data-route="C-13">แชทไรเดอร์</button></div>`)}${card(`<strong class="small">สถานะการเตรียม</strong><div class="step-list">${[["ร้านรับออเดอร์","12:19"],["กำลังปรุงอาหาร","กำลังทำ"],["พร้อมให้ไรเดอร์รับ","ถัดไป"]].map((x,i)=>`<div class="step ${i===0?'done':''}"><span class="step-dot">${i===0?'✓':i+1}</span><div class="step-copy"><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('')}</div>`)}<div class="btn-row">${button('กำลังทำอาหาร',{action:'merchant-cooking',variant:'secondary',small:true})}${button('พร้อมส่ง',{action:'merchant-ready',small:true})}</div><div style="margin-top:8px">${button('ส่งมอบให้ไรเดอร์แล้ว',{action:'merchant-handover',variant:'ghost'})}</div>${button('แจ้งเมนูหมด',{action:'toast-out-of-stock',variant:'ghost'})}`;
    case "M-06": return `${head(id,'เมนูของร้าน','จัดการสถานะขายและลำดับเมนู')}${card(`<div class="row-between"><strong>เชื่อม Smart Kitchen</strong>${badge('ซิงก์ล่าสุด 12:10','success')}</div><div class="muted micro">เมนูที่เชื่อมอยู่จะปรับสต็อกตามระบบครัว</div><button class="text-btn" data-route="M-10">ตั้งค่าการเชื่อมต่อ</button>`)}<div class="chip-list"><button class="chip active">ทั้งหมด 18</button><button class="chip">จานเดียว 8</button><button class="chip">เครื่องดื่ม 4</button><button class="chip">หมดชั่วคราว 1</button></div>${MENU.map((m,i)=>card(`<div class="row"><div class="restaurant-thumb" style="width:58px;height:58px;flex-basis:58px;background-image:url('${m.photo}')"></div><div style="flex:1"><strong class="small">${m.name}</strong><div class="muted micro">฿${m.price} · ${m.category}</div>${ctx.soldOut?.has(i)?badge('หมดชั่วคราว','danger'):badge('กำลังขาย','success')}</div><button class="switch ${ctx.soldOut?.has(i)?'':'on'}" data-action="toggle-menu" data-menu="${i}"></button></div>`)).join('')}${button('＋ เพิ่มเมนูใหม่',{route:'M-07'})}${ctx.nav('M')}`;
    case "M-07": return `${head(id,'เพิ่มเมนูใหม่','กรอกข้อมูลให้ลูกค้าเลือกได้ง่าย')}${card(`${field('ชื่อเมนู','เช่น กะเพราหมูกรอบไข่ดาว')}${field('ราคา (บาท)','89','number')}${field('หมวดหมู่','จานเดียว')}${textArea('รายละเอียดเมนู','วัตถุดิบ รสชาติ หรือปริมาณ')}${button('＋ เพิ่มรูปเมนู',{action:'toast-upload',variant:'secondary'})}<div class="form-field"><label>การจัดการสต็อก</label><div class="row-between"><span class="small">ซิงก์กับ Smart Kitchen</span><button class="switch on" data-action="toggle"></button></div></div><button class="text-btn" data-route="M-08">＋ เพิ่มกลุ่มตัวเลือก</button>${keyboardDemo()}`)}<div class="sticky-action">${button('บันทึกเมนู',{action:'save-menu'})}</div>`;
    case "M-08": return `${head(id,'กลุ่มตัวเลือก','เพิ่มตัวเลือกให้ลูกค้าปรับเมนู')}${card(`<div class="row-between"><strong>เลือกระดับความเผ็ด</strong>${badge('บังคับเลือก','warning')}</div>${['ไม่เผ็ด','เผ็ดน้อย','เผ็ดปกติ','เผ็ดมาก'].map((x,i)=>`<div class="row-between info-row"><span>${x}</span><strong>฿0</strong><button class="icon-btn" style="width:38px;height:38px">⋯</button></div>`).join('')}<button class="text-btn" data-action="add-option">＋ เพิ่มตัวเลือก</button>`)}${card(`<div class="row-between"><strong>เพิ่มท็อปปิ้ง</strong>${badge('เลือกได้สูงสุด 3','brand')}</div>${['ไข่ดาว','ไข่เจียว','เพิ่มหมูกรอบ'].map((x,i)=>`<div class="row-between info-row"><span>${x}</span><strong>+฿${[12,15,25][i]}</strong></div>`).join('')}`)}${button('บันทึกกลุ่มตัวเลือก',{action:'save-options'})}`;
    case "M-09": return `${head(id,'ข้อมูลร้าน','รายละเอียดที่ลูกค้าเห็น')}${card(`<div class="food-image" style="border-radius:18px;min-height:125px;background-image:url('${PHOTOS.food2}')"></div>${field('ชื่อร้าน',PEOPLE.merchant.name,'text',PEOPLE.merchant.name)}${field('เบอร์โทรร้าน',PEOPLE.merchant.phone,'tel')}${field('ที่อยู่ร้าน',ADDRESS.split(',')[0],'text')}${textArea('คำแนะนำการเดินทาง','เข้าซอย 50 เมตร ร้านอยู่ซ้ายมือ')}`)}${card(`<strong>เวลาเปิดร้าน</strong>${infoRows([["จันทร์–ศุกร์","09:00–21:30"],["เสาร์–อาทิตย์","10:00–22:00"],["วันหยุดพิเศษ","ปิด 13 ต.ค. 2569"]])}<button class="text-btn" data-action="edit-hours">แก้ไขเวลาและวันหยุด</button>`)}${button('บันทึกข้อมูลร้าน',{action:'save-merchant'})}`;
    case "M-10": {
      const st = ctx.state === "มีข้อมูล" || !ctx.state ? "เชื่อมต่อแล้ว" : ctx.state;
      const sk = card(`<div class="row"><span class="state-illustration">${homeIcon("store", 26)}</span><div><strong>Smart Kitchen</strong><div class="muted small">ระบบ POS และจัดการครัวของร้าน</div></div></div>`);
      if (st === "ยังไม่เชื่อม") return `${head(id, "เชื่อม Smart Kitchen", "จัดการเมนูและสต็อกจากระบบครัว")}${sk}${card(`<strong>เชื่อมแล้วได้อะไร</strong>${["ดึงเมนูและราคาจาก Smart Kitchen อัตโนมัติ", "ออเดอร์จากแอปเข้าครัวทันที ไม่ต้องคีย์ซ้ำ", "สต็อกถูกตัดให้เอง เมนูหมดแล้วปิดขายอัตโนมัติ"].map((x) => `<div class="info-row"><span>${x}</span></div>`).join("")}`)}<div class="sticky-action">${button("เชื่อม Smart Kitchen", { action: "sk-connect" })}</div>`;
      if (st === "กำลังเชื่อม") return `${head(id, "เชื่อม Smart Kitchen", "จัดการเมนูและสต็อกจากระบบครัว")}${sk}<div class="state-box" style="min-height:200px"><div><div class="state-illustration">${homeIcon("clock", 30)}</div><strong>กำลังเชื่อมต่อ...</strong><p class="muted small">ตรวจสอบบัญชีร้านและดึงรายการเมนู ใช้เวลาไม่นาน</p></div></div>`;
      if (st === "เชื่อมไม่สำเร็จ") return `${head(id, "เชื่อม Smart Kitchen", "จัดการเมนูและสต็อกจากระบบครัว")}${sk}${card(`<div class="row"><span class="state-illustration">${homeIcon("error", 26)}</span><div><strong>เชื่อมต่อไม่สำเร็จ</strong><div class="muted small">ไม่พบบัญชี Smart Kitchen ที่ตรงกับร้านนี้ ตรวจสอบบัญชีแล้วลองอีกครั้ง</div></div></div>`, "warning")}<div class="sticky-action">${button("ลองอีกครั้ง", { action: "sk-connect" })}<button class="text-btn" data-action="toast-support">ติดต่อทีมช่วยเหลือ</button></div>`;
      const syncFailed = st === "ซิงก์ไม่สำเร็จ";
      return `${head(id, "เชื่อม Smart Kitchen", "จัดการเมนูและสต็อกจากระบบครัว")}${sk}${card(`<div class="row-between" style="margin-top:4px">สถานะการเชื่อมต่อ ${badge(syncFailed ? "ซิงก์ไม่สำเร็จ" : "เชื่อมต่อแล้ว", syncFailed ? "danger" : "success")}</div><div class="muted micro">${syncFailed ? "ซิงก์ล่าสุดไม่สำเร็จ 12:10 น. · ข้อมูลที่เห็นอาจไม่ล่าสุด" : "เชื่อมบัญชีครัวบ้านสวน · อัปเดตล่าสุด 12:10 น."}</div>`)}${card(`<strong>ข้อมูลที่ซิงก์</strong>${infoRows([["รายการเมนู", "18 รายการ"], ["สต็อกเมนู", "อัตโนมัติ"], ["รายการขายจาก Delivery", "ส่งเข้าครัวทันที"], ["สถานะ sync ล่าสุด", syncFailed ? "ล้มเหลว" : "สำเร็จ 12:10 น.", syncFailed ? "danger" : ""]])}<div class="row-between" style="margin-top:10px">${button(syncFailed ? "ลองซิงก์อีกครั้ง" : "ซิงก์เมนูตอนนี้", { action: "sync-menu", variant: "secondary", small: true })}${button("ยกเลิกเชื่อม", { action: "disconnect-sk", variant: "ghost", small: true })}</div>`)}${card(`<div class="muted small">เมนูที่จัดการจาก Smart Kitchen แก้ราคาและสต็อกในแอปนี้ไม่ได้</div>`)}`;
    }
    case "M-11": return `${head(id,'บัญชีรับเงิน','รอบโอนทุกวันอังคารและศุกร์')}${block(`<strong>บัญชีธนาคาร</strong>${infoRows([["ธนาคาร","กสิกรไทย"],["ชื่อบัญชี",PEOPLE.merchant.owner],["เลขบัญชี","xxx-x-xx492-1"],["รอบโอน","อังคาร · ศุกร์"]])}<button class="text-btn" data-action="edit-bank">แก้ไขบัญชีรับเงิน</button>`)}${block(`<strong>ค่าธรรมเนียมแพลตฟอร์ม</strong><div class="muted small">แพลตฟอร์ม 15% ของยอดอาหาร</div><div class="price-line"><span>ยอดขายวันนี้</span><strong>฿8,420</strong></div><div class="price-line"><span>ค่าธรรมเนียมโดยประมาณ</span><strong>฿1,263</strong></div>`, 'tint')}${button('ดูประวัติการโอน',{route:'M-12',variant:'secondary'})}`;
    case "M-12": return `${head(id,'กระเป๋าร้านค้า','ยอดขายและประวัติการรับเงิน')}${card(`<span class="eyebrow">ยอดรอโอน</span><strong style="font-size:28px">฿12,480.50</strong><div class="muted small">โอนรอบถัดไป ศุกร์ 9 ต.ค. 2569</div>`,'tint')}${section('รายการล่าสุด', [['6 ต.ค.','ยอดขาย 24 orders','฿7,840','โอนแล้ว'],['3 ต.ค.','ยอดขาย 19 orders','฿6,240','โอนแล้ว'],['30 ก.ย.','ยอดขาย 21 orders','฿6,980','โอนแล้ว']].map(x=>card(`<div class="row-between"><strong>${x[0]}</strong>${badge(x[3],'success')}</div><div class="row-between muted small"><span>${x[1]}</span><strong style="color:var(--text)">${x[2]}</strong></div><div class="muted micro">ค่าธรรมเนียม ฿${Math.round(Number(x[2].replace('฿','').replace(',',''))*.15)}</div>`)).join(''))}${ctx.nav('M')}`;
    case "M-13": return `${head(id,'รายงานภาพรวม','ยอดขายร้าน · 1–7 ต.ค. 2569')}${card(`<div class="row-between"><span>ยอดขายรวม</span>${badge('↑ 12.8% จากสัปดาห์ก่อน','success')}</div><strong style="font-size:29px">฿56,840</strong><div class="muted small">จากทั้งหมด 186 orders</div>${chart()}`)}<div class="metric-grid"><div class="metric"><span>ค่าเฉลี่ยต่อ order</span><strong>฿306</strong></div><div class="metric"><span>ยกเลิก</span><strong>4.3%</strong></div><div class="metric"><span>เวลาเตรียมเฉลี่ย</span><strong>18 นาที</strong></div><div class="metric"><span>คะแนนร้าน</span><strong>4.8 ★</strong></div></div>${card(`<strong>เมนูขายดี</strong>${infoRows([[MENU[0].name,'84 จาน · ฿7,476'],[MENU[1].name,'51 จาน · ฿6,375'],['ชาไทยเย็น','38 แก้ว · ฿1,710']])}`)}${ctx.nav('M')}`;
    case "M-14": return `${head(id,'รีวิวจากลูกค้า','คะแนนเฉลี่ย 4.8 จาก 1,248 รีวิว')}${card(`<div class="row"><strong style="font-size:32px">4.8</strong><div><span style="color:var(--accent);font-size:20px">★★★★★</span><div class="muted micro">รีวิวเดือนนี้ 126 รายการ</div></div></div>`)}${[["กมลชนก","อาหารร้อน รสชาติเข้มข้น ส่งเร็วด้วยค่ะ","วันนี้ 12:47"],["ปกรณ์","ผัดไทยอร่อยมาก กุ้งสด","เมื่อวาน 19:14"],["ณัฐชา","ชาไทยหวานน้อยกำลังดี","5 ต.ค."]].map(x=>card(`<div class="row-between"><strong>${x[0]}</strong>${badge('★★★★★','warning')}</div><p class="small">${x[1]}</p><div class="row-between muted micro"><span>${x[2]}</span><button class="text-btn" data-action="reply-review">ตอบกลับ</button></div>`)).join('')}`;
    case "M-15": return `${head(id,'โปรโมชันของร้าน','จัดการสิทธิพิเศษให้ลูกค้า')}${card(`<div class="row-between"><strong>ลด 20% สูงสุด ฿40</strong>${badge('กำลังใช้งาน','success')}</div><div class="muted small">ยอดขั้นต่ำ ฿150 · สิ้นสุด 31 ต.ค. 2569</div><div class="muted micro">ใช้แล้ว 84 / 200 สิทธิ์</div>`)}${card(`<strong>คูปองส่งฟรี ฿15</strong><div class="muted small">ใช้ได้เมื่อสั่งครบ ฿180 · 12–31 ต.ค.</div>${badge('ตั้งเวลาไว้','info')}`)}${button('＋ สร้างโปรโมชัน',{action:'create-promo'})}`;
    case "M-16": return `${head(id,'ช่วยเหลือและเคลม','เราพร้อมช่วยตรวจสอบ order')}${card(`<div class="row-between"><strong>เคส #CS-261007-128</strong>${badge('กำลังตรวจสอบ','warning')}</div><div class="small">ลูกค้าแจ้งว่าได้รับเมนูไม่ครบ · ${ORDER_NO}</div><div class="muted micro">เปิดเคส 12:51 น. · เจ้าหน้าที่จะตอบกลับใน 30 นาที</div><button class="text-btn" data-action="toast-support">ดูรายละเอียด / แชทเจ้าหน้าที่</button>`)}${section('หัวข้อช่วยเหลือ',['การชำระเงินและรอบโอน','ออเดอร์ถูกยกเลิก','การเชื่อม Smart Kitchen','การแก้ไขข้อมูลร้าน'].map(x=>card(`<div class="row-between"><span class="small">${x}</span><span>›</span></div>`)).join(''))}${ctx.nav('M')}`;
    case "M-17": {
      const links = [["M-09", "store", "ข้อมูลร้าน"], ["M-10", "sync", "Smart Kitchen"], ["M-11", "wallet", "บัญชีรับเงิน"], ["M-14", "star", "รีวิวจากลูกค้า"], ["M-15", "sparkles", "โปรโมชันของร้าน"]];
      return `${head(id, "บัญชีร้านค้า", "ตั้งค่าและสลับบทบาท")}${profileRow("คบ", PEOPLE.merchant.name, `ผู้ดูแล ${PEOPLE.merchant.owner}`)}${section("จัดการร้าน", listGroup(links.map((x) => listRow({ icon: x[1], label: x[2], attrs: `data-route="${x[0]}"` })).join("")))}${section("ตั้งค่า", settingsGroup(ctx, "เสียงแจ้งเตือนออเดอร์ใหม่"))}${section("โหมดการใช้งาน", roleSwitchRow("เปิด role ลูกค้าและไรเดอร์ด้วยบัญชีเดียวกัน"))}${accountFooter()}${ctx.nav("M")}`;
    }
    default: return `${head(id,'ร้านค้าของฉัน',PEOPLE.merchant.name)}${card(infoRows([["ชื่อร้าน",PEOPLE.merchant.name],["คะแนน","4.8 ★"],["order วันนี้","27"],["สถานะ","เปิดรับ order"]]))}${button('กลับหน้า order',{route:'M-03'})}`;
  }
}
