import { ADDRESS, COUPONS, DESTINATION, MENU, ORDER_NO, PEOPLE, PICKUP, STORES, VEHICLES } from "../data/content.js";
import { appBar, block, badge, button, card, escapeHTML, faq, field, iconButton, section, segmented, sosButton, textArea } from "./components.js";
import { homeIcon } from "./home-icons.js";

const heading = (title, subtitle = "") => `<div class="page-heading"><h2>${title}</h2>${subtitle ? `<p>${subtitle}</p>` : ""}</div>`;
const rowCard = (title, subtitle, route, action = "") => `<button class="p2-row-card" ${route ? `data-route="${route}"` : `data-action="${action}"`}><span><strong>${title}</strong><small>${subtitle}</small></span><span aria-hidden="true">›</span></button>`;
const price = (amount) => `฿${Number(amount || 0).toLocaleString("th-TH")}`;
const ORDER_HISTORY = [["อาหาร", ORDER_NO, "ครัวบ้านสวน รัชดา", "กำลังดำเนินการ", "฿229", "C-12"], ["อาหาร", "RM-261006-0842", "ครัวบ้านสวน รัชดา", "เสร็จแล้ว", "฿194", "C-17"], ["เรียกรถ", "RM-RIDE-261007-63", "ห้วยขวาง → อโศก", "เสร็จแล้ว", "฿86", "C-38"], ["ส่งของ", "RM-261005-2103", "ลาดพร้าว → รัชดา", "ยกเลิก", "฿65", "C-34"]];
const optionRows = (group, items, prices, ctx) => { const order = ctx.optionOrder?.[group] || items.map((_, i) => i); return order.map((i) => { const id = `${group}-${i}`; if (ctx.optionDeleted?.has(id)) return ""; const item = ctx.optionOverrides?.[id] || {}; const name = escapeHTML(item.name || items[i]); return `<div class="row-between info-row" data-reorder-row data-group="${group}" data-option="${i}"><button class="icon-btn" style="touch-action:none;cursor:grab" data-reorder-handle data-group="${group}" data-option="${i}" aria-label="ลากเพื่อเรียงลำดับ ${name}">${homeIcon("drag", 20)}</button><span style="flex:1">${name}</span><strong>${group === "topping" ? "+" : ""}${price(item.price ?? prices[i])}</strong><button class="icon-btn" data-action="p2-option-menu" data-group="${group}" data-option="${i}" aria-label="แก้ไข ${name}">⋮</button></div>`; }).join(""); };

export function renderP2(id, ctx) {
  const top = (title, back = "C-01") => appBar(title, { back: true, route: ctx.previousId || back });
  const subtotal = Number(ctx.subtotal || 0);
  const total = Number(ctx.cartTotal || subtotal + 15 - (ctx.discount || 0));
  const cartCount = (ctx.cart || []).reduce((sum, item) => sum + Number(item.qty || 0), 0);
  const rows = (ctx.orderItems || []).map((item, i) => `<div class="p2-cart-row"><div class="p2-cart-copy"><strong>${item.name}</strong><small>${price(item.price)} / รายการ · ${item.note || "ยังไม่มีหมายเหตุ"}</small><button class="text-btn" data-action="p2-edit-cart" data-index="${i}">แก้ไขตัวเลือก</button></div><div class="counter"><button data-action="cart-minus" data-index="${i}" aria-label="ลดจำนวน">−</button><strong>${item.qty}</strong><button data-action="cart-plus" data-index="${i}" aria-label="เพิ่มจำนวน">＋</button></div></div>`).join("");

  switch (id) {
    case "C-01": return `${appBar("ส่งถึงที่อยู่", { subtitle: ADDRESS.split(",")[0], back: false })}<div class="p2-home-search"><button class="searchbox" data-route="C-05"><span>⌕</span><span class="muted small">ค้นหาร้าน เมนู หรือบริการ</span></button></div>${ctx.orderStep > 0 ? section("ออเดอร์ที่กำลังดำเนินอยู่", card(`<div class="row-between"><strong>${ORDER_NO}</strong>${badge(ctx.orderLabel, "warning")}</div><div class="muted small">${PEOPLE.merchant.name} · ถึงประมาณ 12:45 น.</div>${button("ติดตามออเดอร์", { route: "C-12", variant: "secondary" })}`)) : ""}${section("บริการ", `<div class="metric-grid"><button class="card tint" data-route="C-04"><strong>สั่งอาหาร</strong><div class="muted micro">ร้านใกล้คุณ</div></button><button class="card" data-route="C-33"><strong>เรียกรถ</strong><div class="muted micro">รับส่งคน</div></button></div>`)}${section("ร้านแนะนำ", STORES.slice(0, 3).map((s) => rowCard(s.name, `${s.cuisine} · ${s.eta} · ★ ${s.rating}`, "C-06")).join(""))}${cartCount ? `<div class="p2-cart-fab">${button(`ตะกร้า · ${cartCount} รายการ · ${price(total)}`, { route: "C-08" })}</div>` : ""}${ctx.nav("C")}`;

    case "C-02": return `${top("เลือกที่อยู่จัดส่ง")}${heading("ส่งอาหารไปที่ไหน?", "เลือกที่อยู่แล้วกลับไปทำรายการต่อ")}${card(`<div class="p2-address-row"><strong>บ้าน · ห้วยขวาง</strong><small>${ADDRESS}</small>${button("เลือกที่อยู่นี้", { action: "p2-select-address", variant: "secondary" })}</div>`)}${["ที่ทำงาน · อโศก", "คอนโดเพื่อน · ลาดพร้าว"].map((label) => card(`<div class="p2-address-row"><strong>${label}</strong><small>กรุงเทพมหานคร</small>${button("เลือกที่อยู่นี้", { action: "p2-select-address", variant: "ghost" })}</div>`)).join("")}${button("＋ เพิ่มที่อยู่ใหม่", { route: "C-03" })}`;

    case "C-08": return `${top("ตะกร้าของคุณ")}${heading("ตรวจรายการก่อนสั่ง", `${PEOPLE.merchant.name} · ส่งถึง ${ADDRESS.split(",")[0]}`)}${ctx.cart?.length ? `<div class="cart-list">${rows}</div><button class="text-btn" data-route="C-06">＋ เพิ่มรายการ</button><div class="price-block"><div class="price-line"><span>ค่าอาหาร</span><strong>${price(subtotal)}</strong></div><div class="price-line"><span>ค่าส่ง + ค่าบริการ</span><strong>฿15</strong></div><div class="price-line total"><span>ยอดชำระโดยประมาณ</span><strong>${price(total)}</strong></div></div>` : card(`<strong>ตะกร้ายังว่าง</strong><p class="muted small">เลือกเมนูที่ชอบจากร้านใกล้บ้าน</p>${button("เลือกร้านอาหาร", { route: "C-04" })}`)}<div class="sticky-action">${button("ไปหน้าชำระเงิน", { route: "C-09", disabled: !ctx.cart?.length || subtotal < 99 })}</div>`;

    case "C-09": return `${top("ตรวจสอบและชำระ")}${heading("สรุปคำสั่งซื้อ", "คาดว่าจะได้รับภายใน 20–30 นาที")}${block(`<div class="row-between"><strong>ที่อยู่จัดส่ง</strong>${button("เปลี่ยน", { route: "C-02", variant: "ghost", small: true })}</div><div class="muted small">${ADDRESS}</div>`)}${block(`<strong>รายการอาหาร</strong>${(ctx.orderItems || []).map((x) => `<div class="price-line"><span>${x.name} × ${x.qty}</span><strong>${price(x.price * x.qty)}</strong></div>`).join("")}`)}${block(`<div class="row-between"><strong>วิธีชำระเงิน</strong><button class="text-btn" data-action="p2-payment-method">${ctx.paymentMethod || "พร้อมเพย์ QR"} · เปลี่ยน</button></div><div class="muted micro">เลือกวิธีชำระก่อนยืนยันรายการ</div>`)}${block(`<div class="row-between"><strong>ส่วนลด</strong>${button("เลือกโค้ด", { route: "C-10", variant: "ghost", small: true })}</div><div class="muted small">${ctx.coupon || "ยังไม่ได้ใช้โค้ดส่วนลด"}</div><div class="price-line"><span>ค่าอาหาร</span><strong>${price(subtotal)}</strong></div><div class="price-line"><span>ค่าส่ง + ค่าบริการ</span><strong>฿15</strong></div>${ctx.discount ? `<div class="price-line"><span>ส่วนลด</span><strong>−${price(ctx.discount)}</strong></div>` : ""}<div class="price-line total"><span>ยอดสุทธิ</span><strong>${price(total)}</strong></div>`)}<div class="sticky-action">${button(`ยืนยันสั่งอาหาร · ${price(total)}`, { action: "p2-confirm-order" })}</div>`;

    case "C-10": return `${top("โค้ดส่วนลด")}${heading("ใช้โค้ดส่วนลด", "กรอกโค้ดหรือเลือกคูปองที่ใช้ได้")}${card(`<div class="p2-coupon-entry"><input class="field" data-coupon-code placeholder="กรอกโค้ดส่วนลด" aria-label="กรอกโค้ดส่วนลด"><button class="btn inline" data-action="apply-manual-coupon">ใช้โค้ด</button></div>`)}${COUPONS.map((c, i) => card(`<div class="row-between"><div><strong>${c.title}</strong><div class="muted small">${c.sub}</div><code class="pill brand">${c.code}</code></div>${button(c.disabled ? "ใช้ไม่ได้" : "ใช้โค้ด", { action: "apply-coupon", variant: c.disabled ? "ghost" : "", small: true, disabled: c.disabled })}</div>${c.disabled ? `<div class="p2-reason">ยอดขั้นต่ำ ฿300 · ยังขาดอีก ฿${Math.max(0, 300 - subtotal)}</div>` : ""}`, "coupon-card")).join("")}`;

    case "C-12": {
      // Sheet layout (D-025): flat rows split by dividers · actions kept: sheet-toggle, toast-call, chat (C-13), order menu → C-14
      const open = Boolean(ctx.trackOpen);
      const canCancel = ctx.orderStep < 4 && !ctx.orderCancelled;
      const items = (ctx.orderItems || []).map((x) => `<div class="track-item"><span>${x.name}</span><span class="muted">× ${x.qty}</span></div>`).join("");
      const steps = `<div class="step-list">${(ctx.orderSteps || []).map((s, i) => `<div class="step ${i < ctx.orderStep ? "done" : ""}"><span class="step-dot">${i < ctx.orderStep ? homeIcon("check", 16) : i + 1}</span><div class="step-copy"><strong>${s[0]}</strong><small>${s[1]}</small></div></div>`).join("")}</div>`;
      return `${top("ติดตามคำสั่งซื้อ")}<div class="map-card map-full"><span class="pill" style="position:absolute;top:12px;left:12px">${ctx.orderLabel}</span></div><section class="tracking-sheet" aria-label="สถานะคำสั่งซื้อ"><button class="track-handle" data-action="sheet-toggle" data-sheet-handle aria-expanded="${open}" aria-label="${open ? "ย่อรายละเอียด" : "ดูรายละเอียดสถานะ"}"><div class="sheet-handle"></div></button><div class="track-row track-eta"><div><small class="muted">ถึงโดยประมาณ</small><strong>12:45 น.</strong></div><div class="row">${badge(ctx.orderLabel, ctx.orderCancelled ? "danger" : "brand")}${canCancel ? iconButton("more", "ตัวเลือกคำสั่งซื้อ", 'data-action="p2-order-menu"') : ""}</div></div>${ctx.orderMenuOpen && canCancel ? `<div class="track-row">${button("ยกเลิกคำสั่งซื้อ", { route: "C-14", variant: "danger" })}</div>` : ""}<div class="track-row track-courier"><span class="avatar">${PEOPLE.courier.initials}</span><div class="track-courier-copy"><strong class="small">${PEOPLE.courier.name}</strong><small class="muted">${PEOPLE.courier.bike} · ${PEOPLE.courier.plate}</small></div>${iconButton("call", "โทรหาไรเดอร์", 'data-action="toast-call"')}${iconButton("message", "แชทกับไรเดอร์", 'data-route="C-13"')}</div>${open ? `${ctx.hasBundle ? `<div class="p2-bundle-note">ไรเดอร์แวะส่งอีกออเดอร์ในเส้นทาง · ETA ปรับแล้ว</div>` : ""}<div class="track-row track-block"><strong class="small">สถานะ</strong>${steps}</div><div class="track-row track-block"><div class="row-between"><strong class="small">รายการอาหาร</strong><small class="muted">${ORDER_NO}</small></div>${items}</div>` : `<div class="muted micro track-hint">แตะหรือลากที่จับเพื่อดูสถานะและรายการอาหาร</div>`}</section>`;
    }

    case "C-14": return `${top("ยกเลิกคำสั่งซื้อ", "C-12")}${heading("เลือกเหตุผลการยกเลิก", "ตรวจสอบผลกระทบก่อนยืนยัน")}<div class="list-group" role="radiogroup" aria-label="เหตุผลการยกเลิก">${["เปลี่ยนใจ", "ที่อยู่จัดส่งไม่ถูกต้อง", "สั่งซ้ำโดยไม่ตั้งใจ", "ร้านใช้เวลานานกว่าที่แจ้ง", "อื่น ๆ"].map((x) => { const on = x === (ctx.cancelReason || "เปลี่ยนใจ"); return `<button class="opt-row" role="radio" aria-checked="${on}" data-action="cancel-reason" data-value="${x}"><span class="opt-control radio" aria-hidden="true"></span><span class="opt-label">${x}</span></button>`; }).join("")}</div><div data-cancel-other ${ctx.cancelReason === "อื่น ๆ" ? "" : "hidden"}>${textArea("ระบุเหตุผล", "กรุณาระบุเพิ่มเติม")}</div>${card(`<strong>ผลการคืนเงิน</strong><div class="muted small">${ctx.orderStep >= 3 ? "ร้านเริ่มเตรียมอาหารแล้ว · อาจไม่ได้รับเงินคืน" : `คืนเงิน ${price(subtotal + 15 - (ctx.discount || 0))} เข้าช่องทางเดิมภายใน 3–5 วันทำการ`}</div>`, "warning")}${button("ยืนยันยกเลิกคำสั่งซื้อ", { action: "cancel-order", variant: "danger" })}${button("กลับไปติดตาม", { route: "C-12", variant: "ghost" })}`;

    case "C-15": return `${top("ได้รับอาหารแล้ว")}${heading("ให้คะแนนประสบการณ์", "ขอบคุณที่ช่วยให้บริการดีขึ้น")}${card(`<strong>ร้านอาหาร · ${PEOPLE.merchant.name}</strong><div class="p2-rating">${[1, 2, 3, 4, 5].map((n) => `<button data-action="rate" data-value="${n}" aria-label="${n} ดาว">★</button>`).join("")}</div><small class="muted">รสชาติ · ความคุ้มค่า · บรรจุภัณฑ์</small>`)}${card(`<strong>ไรเดอร์ · ${PEOPLE.courier.name}</strong><div class="p2-rating">${[1, 2, 3, 4, 5].map((n) => `<button data-action="rate" data-value="${n}" aria-label="${n} ดาว">★</button>`).join("")}</div><strong class="small">เพิ่มทิป</strong><div class="chip-list">${[10, 20, 50].map((n) => `<button class="chip ${Number(ctx.tipAmount) === n ? "active" : ""}" data-action="p2-tip" data-tip="${n}">${price(n)}</button>`).join("")}<button class="chip" data-action="p2-tip-custom">กำหนดเอง</button></div>${ctx.tipCustom ? `<input class="field" type="number" min="0" data-tip-custom placeholder="จำนวนทิป">` : ""}`)}<div class="row">${button("ส่งคะแนน", { action: "submit-rating" })}${button("ข้าม", { route: "C-01", variant: "ghost" })}</div>`;

    case "C-16": { const items = ORDER_HISTORY.filter((x) => (ctx.historyService || "ทั้งหมด") === "ทั้งหมด" || x[0] === ctx.historyService).filter((x) => (ctx.historyFilter || "ทั้งหมด") === "ทั้งหมด" || x[3] === ctx.historyFilter); return `${top("ประวัติรายการ", "C-01")}${heading("รายการของคุณ", "กรองตามบริการและสถานะ")}${ctx.nav("C")}<div class="chip-list">${["ทั้งหมด", "อาหาร", "เรียกรถ", "ส่งของ"].map((x) => `<button class="chip ${x === (ctx.historyService || "ทั้งหมด") ? "active" : ""}" data-action="p2-history-service" data-service="${x}">${x}</button>`).join("")}</div><div class="chip-list">${["ทั้งหมด", "กำลังดำเนินการ", "เสร็จแล้ว", "ยกเลิก"].map((x) => `<button class="chip ${x === (ctx.historyFilter || "ทั้งหมด") ? "active" : ""}" data-action="p2-history-filter" data-filter="${x}">${x}</button>`).join("")}</div>${items.map((x) => rowCard(`${x[0]} · ${x[3]} · ${x[4]}`, `${x[2]} · ${x[1]}`, x[5])).join("") || card("ไม่พบรายการตามตัวกรอง")}`; }

    case "C-18": return `${top("กล่องข้อความ", "C-01")}${heading("แชทและการแจ้งเตือน", "ข้อความใหม่จะแสดงจุดแจ้งเตือน")}${ctx.nav("C")}<div class="chip-list"><button class="chip ${ctx.messageTab !== "แจ้งเตือน" ? "active" : ""}" data-action="p2-message-tab" data-tab="แชท">แชท <span class="p2-unread-dot"></span></button><button class="chip ${ctx.messageTab === "แจ้งเตือน" ? "active" : ""}" data-action="p2-message-tab" data-tab="แจ้งเตือน">แจ้งเตือน</button></div>${ctx.messageTab === "แจ้งเตือน" ? [["สถานะ order", "ไรเดอร์รับอาหารแล้ว กำลังเดินทางถึงคุณ", "12:38", "C-12"], ["โปรโมชันประจำสัปดาห์", "ลด 20% สูงสุด ฿40 ที่ร้านใกล้บ้าน", "เมื่อวาน", "C-04"]].map((x) => rowCard(x[0], `${x[1]} · ${x[2]}`, x[3])).join("") : rowCard("แชทกับไรเดอร์", "มีข้อความใหม่ · กำลังเดินทางมาส่ง", "C-13")}`;

    case "C-33": return `${top("จุดรับและปลายทาง")}${heading("กำหนดเส้นทาง", "เลือกจุดรับและปลายทางให้ถูกต้อง")}${card(`<div class="row-between"><strong>จุดรับ</strong>${button("เลือกจากแผนที่", { route: "C-03", variant: "ghost", small: true })}</div>${field("จุดรับ", "ค้นหาจุดรับ", "text", ctx.ridePickup || ADDRESS.split(",")[0])}<div class="chip-list"><button class="chip" data-action="p2-set-pickup" data-value="บ้าน · ห้วยขวาง">บ้าน</button><button class="chip" data-action="p2-set-pickup" data-value="ที่ทำงาน · อโศก">ที่ทำงาน</button></div><div class="row-between"><strong>ปลายทาง</strong><button class="icon-btn" data-action="p2-swap-route" aria-label="สลับจุดรับและปลายทาง">⇅</button></div>${field("ปลายทาง", "ค้นหาปลายทาง", "text", ctx.rideDestination || DESTINATION)}<div class="chip-list"><button class="chip" data-action="p2-set-destination" data-value="อโศก ทาวเวอร์">อโศก</button><button class="chip" data-action="p2-set-destination" data-value="เซ็นทรัลพระราม 9">พระราม 9</button></div>`)}<div class="sticky-action">${button("เลือกประเภทรถ", { route: "C-35" })}</div>`;

    case "C-35": { const ride = VEHICLES.find((v) => v.id === ctx.selectedVehicle) || VEHICLES[1]; const fare = ride.price - (ctx.rideCouponApplied ? 10 : 0); return `${top("เลือกประเภทรถ", "C-33")}${heading("เดินทางแบบที่เหมาะกับคุณ", "ห้วยขวาง → อโศก · 8.4 กม.")}${VEHICLES.map((v) => card(`<button class="p2-vehicle-choice ${v.id === ride.id ? "selected" : ""}" data-action="p2-select-vehicle" data-vehicle="${v.id}"><span class="p2-vehicle-icon">${homeIcon(v.id === "motorbike" ? "bike" : "car", 24)}</span><span><strong>${v.name}</strong><small>${v.seats} ที่นั่ง · ถึงใน ${v.eta}</small></span><strong>${price(v.price)}</strong></button>`)).join("")}${card(`<div class="row-between"><strong>วิธีชำระ</strong><button class="text-btn" data-action="p2-ride-payment">${ctx.ridePayment || "พร้อมเพย์"} · เปลี่ยน</button></div><div class="row-between"><strong>ส่วนลด</strong>${button(ctx.rideCouponApplied ? "RIDE10 · ใช้แล้ว" : "เลือกโค้ด", { action: "ride-coupon-sheet", variant: "secondary", small: true })}</div>`)}<div class="sticky-action">${button(`ยืนยันเรียกรถ · ${price(fare)}`, { route: "C-36" })}</div>`; }

    case "C-38": { const ride = VEHICLES.find((v) => v.id === ctx.selectedVehicle) || VEHICLES[1]; const fare = ride.price - (ctx.rideCouponApplied ? 10 : 0); return `${top("ถึงปลายทางแล้ว")}${heading(ctx.ridePaid ? "ชำระเงินแล้ว" : "เดินทางเรียบร้อย", ctx.ridePaid ? "ให้คะแนนและตรวจสอบใบเสร็จได้" : "ตรวจสอบและชำระค่าโดยสาร")}${card(`<div class="row-between"><strong>ค่าโดยสาร · ${ride.name}</strong><strong style="font-size:24px">${price(fare)}</strong></div><div class="muted small">ห้วยขวาง → อโศก · 8.4 กม. · 27 นาที</div><div class="info-row"><span>วิธีชำระ</span><strong>${ctx.ridePayment || "พร้อมเพย์"}</strong></div>${ctx.rideCouponApplied ? `<div class="info-row"><span>ส่วนลด RIDE10</span><strong>−฿10</strong></div>` : ""}<div class="row-between"><span>สถานะ</span>${badge(ctx.ridePaid ? "ชำระแล้ว" : ctx.ridePayment === "เงินสด" ? "รอเก็บเงินสด" : "รอชำระผ่าน QR", ctx.ridePaid ? "success" : "warning")}</div>${!ctx.ridePaid ? button(ctx.ridePayment === "เงินสด" ? `ยืนยันรับเงินสด ${price(fare)}` : `ตรวจสอบการชำระ ${price(fare)}`, { action: "p2-ride-paid" }) : ""}`)}${ctx.ridePaid ? `${card(`<strong>ให้คะแนนคนขับ ${PEOPLE.courier.name}</strong><div class="p2-rating">${[1, 2, 3, 4, 5].map((n) => `<button data-action="rate" data-value="${n}" aria-label="${n} ดาว">★</button>`).join("")}</div><strong class="small">เพิ่มทิป</strong><div class="chip-list">${[10, 20, 50].map((n) => `<button class="chip ${Number(ctx.tipAmount) === n ? "active" : ""}" data-action="p2-tip" data-tip="${n}">${price(n)}</button>`).join("")}<button class="chip" data-action="p2-tip-custom">กำหนดเอง</button></div>${ctx.tipCustom ? `<input class="field" type="number" min="0" data-tip-custom placeholder="จำนวนทิป">` : ""}`)}<div class="row">${button("ส่งคะแนน", { action: "submit-rating" })}${button("ข้าม", { route: "C-01", variant: "ghost" })}</div>${button("ดูใบเสร็จ", { action: "ride-receipt", variant: "ghost" })}` : ""}`; }

    case "M-01": {
      const step = Math.max(0, Math.min(2, Number(ctx.merchantSignupStep || 0)));
      const labels = ["ข้อมูลร้าน", "เอกสาร", "บัญชีรับเงิน"];
      const body = step === 0 ? `${field("ชื่อร้าน", "ชื่อร้านของคุณ")}${field("ชื่อผู้ติดต่อ", "ชื่อ-นามสกุล")}${field("เบอร์โทรศัพท์ร้าน", "08x-xxx-xxxx", "tel")}${field("ที่อยู่ร้าน", "เลขที่ ซอย แขวง เขต จังหวัด")}` : step === 1 ? `<div class="p2-upload-row">หนังสือรับรองร้านค้า ${badge("ยังไม่แนบ", "warning")}${button("แนบเอกสาร", { action: "toast-upload", variant: "secondary", small: true })}</div><div class="p2-upload-row">บัตรประชาชนผู้สมัคร ${badge("ยังไม่แนบ", "warning")}${button("แนบเอกสาร", { action: "toast-upload", variant: "secondary", small: true })}</div>` : `${field("ชื่อบัญชี", "ชื่อให้ตรงกับผู้สมัคร")}${field("เลขบัญชี", "กรอกเลขบัญชี", "text")}${field("ธนาคาร", "เลือกธนาคาร")}`;
      return `${top("สมัครร้านค้า", "C-19")}${heading("สมัครเป็นร้านค้า", `ขั้นที่ ${step + 1} จาก 3 · ${labels[step]}`)}<div class="p2-progress">${labels.map((x, i) => `<div class="${i <= step ? "active" : ""}"><span>${i + 1}</span><small>${x}</small></div>`).join("")}</div>${card(body)}<div class="row">${step ? button("ย้อนกลับ", { action: "p2-wizard-back", variant: "ghost" }) : ""}${button(step === 2 ? "ส่งใบสมัคร" : "ดำเนินการต่อ", { action: step === 2 ? "toast-next-step" : "p2-wizard-next" })}</div>`;
    }

    case "M-04": return `${appBar("ออเดอร์ใหม่เข้าแล้ว", { subtitle: "รับภายใน 45 วินาที", back: false })}<div class="state-box" style="min-height:130px"><div class="offer-countdown" style="width:104px;height:104px;font-size:26px" role="timer" data-live-countdown="45" data-expire-go="M-03" data-expire-msg="หมดเวลารับออเดอร์ ออเดอร์ถูกส่งต่อแล้ว">00:45</div></div>${card(`<div class="row-between"><strong>${ORDER_NO}</strong><strong style="font-size:22px">${price(subtotal)}</strong></div><div class="muted small">ลูกค้า ${PEOPLE.customer.short} · ส่งถึง ${ADDRESS.split(",")[0]}</div>${(ctx.orderItems || []).map((x) => `<div class="info-row"><span>${x.name} × ${x.qty}</span><strong>${price(x.price * x.qty)}</strong></div>`).join("")}<strong class="small">เวลาเตรียมอาหาร</strong><div class="chip-list">${[15, 20, 30].map((n) => `<button class="chip ${Number(ctx.prepMinutes || 20) === n ? "active" : ""}" data-action="p2-prep-time" data-minutes="${n}">${n} นาที</button>`).join("")}</div>`)}<div class="sticky-action">${button("รับออเดอร์", { route: "M-05" })}<button class="text-btn" style="display:block;margin:8px auto 0" data-action="merchant-decline">ปฏิเสธออเดอร์</button></div>`;

    case "M-05": return `${top("รายละเอียดออเดอร์", "M-03")}${card(`<div class="row-between"><strong>${ORDER_NO}</strong>${badge(ctx.merchantStatus === "พร้อมส่ง" ? "พร้อมส่ง" : "กำลังทำ", ctx.merchantStatus === "พร้อมส่ง" ? "success" : "warning")}</div><div class="row-between"><div class="muted small">${PEOPLE.customer.short} · ส่งถึง ${ADDRESS.split(",")[0]}</div>${iconButton("message", "แชทกับไรเดอร์", 'data-route="C-13"')}</div>${(ctx.orderItems || []).map((x) => `<div class="p2-order-item"><span><strong>${x.name}</strong><small>× ${x.qty}</small></span><button class="chip" data-action="p2-menu-stock" data-menu="${x.index}">${ctx.soldOut?.has(x.index) ? "แจ้งพร้อมขาย" : "แจ้งเมนูหมด"}</button></div>`).join("")}${button(ctx.merchantStatus === "พร้อมส่ง" ? "ส่งมอบให้ไรเดอร์" : "อาหารพร้อมแล้ว", { action: ctx.merchantStatus === "พร้อมส่ง" ? "merchant-handover" : "merchant-status-next" })}`)}`;

    case "M-06": {
      // Flat list rows (D-025) · actions kept: M-10 settings, p2-edit-menu (row → M-07), toggle-menu, add → M-07
      const linked = (ctx.screenStates?.["M-10"] || "เชื่อมต่อแล้ว") === "เชื่อมต่อแล้ว";
      const rows = MENU.map((m, i) => { if (ctx.menuDeleted?.has(i)) return ""; const sold = ctx.soldOut?.has(i); return `<article class="m-menu-row${sold ? " is-sold-out" : ""}"><button class="m-menu-main" data-action="p2-edit-menu" data-menu="${i}" aria-label="แก้ไข ${m.name}"><span class="m-menu-thumb" style="background-image:url('${m.photo}')"></span><span class="m-menu-copy"><strong class="small">${m.name}</strong><small class="muted">${price(m.price)} · ${m.category}</small>${badge(sold ? "หมดชั่วคราว" : "กำลังขาย", sold ? "danger" : "success")}</span></button>${linked ? `<span class="m-menu-lock muted micro">จัดการจาก<br>Smart Kitchen</span>` : `<button class="switch ${sold ? "" : "on"}" data-action="toggle-menu" data-menu="${i}" aria-label="เปิดหรือปิดขาย ${m.name}"></button>`}</article>`; }).join("");
      return `${top("เมนูของร้าน", "M-03")}${heading("จัดการเมนู", "แก้ไขข้อมูลหรือสถานะขาย")}${card(`<div class="row-between"><strong>เชื่อม Smart Kitchen</strong>${badge(linked ? "ซิงก์ล่าสุด 12:10" : "ยังไม่เชื่อม", linked ? "success" : "warning")}</div><div class="muted micro">${linked ? "สถานะขายและสต็อกจัดการจาก Smart Kitchen · แก้ไขรายละเอียดเมนูได้ที่นี่" : "เชื่อมเพื่อให้สต็อกปรับตามระบบครัวอัตโนมัติ"}</div><button class="text-btn" data-route="M-10">ตั้งค่าการเชื่อมต่อ</button>`)}<div class="m-menu-list">${rows}</div><div class="sticky-action">${button("＋ เพิ่มเมนูใหม่", { route: "M-07", variant: "secondary" })}</div>${ctx.nav("M")}`;
    }

    case "M-07": { const m = MENU[Number(ctx.menuIndex || 0)] || MENU[0]; return `${top("แก้ไขเมนู", "M-06")}${card(`<div class="p2-image-preview" style="background-image:url('${m.photo}')"></div>${button("เปลี่ยนรูปเมนู", { action: "toast-upload", variant: "secondary" })}${field("ชื่อเมนู", "ชื่อเมนู", "text", m.name)}${field("ราคา (บาท)", "ราคา", "number", String(m.price))}<div class="form-field"><label>หมวดหมู่</label><div class="chip-list">${["จานเดียว", "กับข้าว", "เครื่องดื่ม", "ของหวาน"].map((c) => `<button class="chip ${c === m.category ? "active" : ""}" data-action="seg">${c}</button>`).join("")}</div></div>${textArea("รายละเอียดเมนู", "รายละเอียด", m.desc)}${button("กลุ่มตัวเลือก", { route: "M-08", variant: "secondary" })}`)}<div class="sticky-action"><div class="row">${button("ลบเมนู", { action: "p2-delete-menu", variant: "danger" })}${button("บันทึก", { action: "save-menu" })}</div></div>`; }

    case "M-08": return `${top("กลุ่มตัวเลือก", "M-07")}${heading("จัดการตัวเลือก", "แก้ชื่อ ราคา กฎ และลำดับของแต่ละกลุ่ม")}${card(`<div class="row-between"><strong>ระดับความเผ็ด</strong><button class="chip" data-action="p2-toggle-required">${ctx.optionRequired === false ? "เลือกได้" : "บังคับเลือก"}</button></div>${optionRows("spice", ["ไม่เผ็ด", "เผ็ดน้อย", "เผ็ดปกติ", "เผ็ดมาก"], [0, 0, 0, 0], ctx)}${button("＋ เพิ่มตัวเลือก", { action: "add-option", variant: "secondary" })}`)}${card(`<div class="row-between"><strong>ท็อปปิ้ง</strong><span class="pill brand">เลือกได้สูงสุด 3</span></div>${optionRows("topping", ["ไข่ดาว", "ไข่เจียว", "เพิ่มหมูกรอบ"], [12, 15, 25], ctx)}`)}${(ctx.customOptionGroups || []).map((name) => card(`<div class="row-between"><strong>${escapeHTML(name)}</strong><button class="chip" data-action="p2-toggle-required">บังคับเลือก</button></div><div class="muted small">เพิ่มตัวเลือกในกลุ่มนี้ได้</div>${button("＋ เพิ่มตัวเลือก", { action: "add-option", variant: "secondary" })}`)).join("")}${button("＋ เพิ่มกลุ่มตัวเลือก", { action: "p2-add-option-group", variant: "secondary" })}${button("บันทึกกลุ่มตัวเลือก", { action: "save-options" })}`;

    case "M-09": return `${top("ข้อมูลร้าน", "M-17")}${block(`<div class="p2-image-preview" style="background-image:url('${STORES[0].photo}')"></div>${button("เปลี่ยนรูปปกร้าน", { action: "toast-upload", variant: "secondary" })}${field("ชื่อร้าน", PEOPLE.merchant.name, "text", PEOPLE.merchant.name)}${field("เบอร์โทรร้าน", PEOPLE.merchant.phone, "tel")}${field("ที่อยู่ร้าน", ADDRESS.split(",")[0], "text", ADDRESS.split(",")[0])}<div class="map-card"><div class="map-pin" style="top:40%;left:48%"><span>ร้าน</span></div><span class="pill" style="position:absolute;bottom:10px;left:10px">ปักหมุดตำแหน่งร้าน</span></div>${textArea("คำแนะนำการเดินทาง", "จุดสังเกตหน้าร้าน")}`)}${button("บันทึกข้อมูลร้าน", { action: "save-merchant" })}`;

    case "M-13": return `${top("รายงานภาพรวม", "M-03")}${heading("รายงานยอดขาย", `ช่วง ${ctx.reportRange || "7 วัน"}`)}<div class="chip-list">${["วันนี้", "7 วัน", "30 วัน", "กำหนดเอง"].map((x) => `<button class="chip ${x === (ctx.reportRange || "7 วัน") ? "active" : ""}" data-action="p2-report-range" data-range="${x}">${x}</button>`).join("")}</div>${card(`<div class="row-between"><strong>ยอดขายรวม</strong>${badge("↑ 12.8%", "success")}</div><strong style="font-size:28px">${price(ctx.reportRange === "วันนี้" ? 8420 : ctx.reportRange === "30 วัน" ? 184260 : 56840)}</strong><div class="muted small">${ctx.reportRange === "วันนี้" ? "27 ออเดอร์" : "186 ออเดอร์"}</div><div class="chart">${[36, 55, 44, 79, 61, 95, 72].map((v, i) => `<button class="chart-bar" style="height:${v}%" data-action="p2-chart-value" data-value="${[4800, 6200, 5100, 7200, 6400, 9200, 7840][i]}"><small>${["จ.", "อ.", "พ.", "พฤ.", "ศ.", "ส.", "อา."][i]}</small></button>`).join("")}</div>${ctx.chartValue ? `<div class="pill info">ยอดวันที่เลือก ${price(ctx.chartValue)}</div>` : ""}`)}${ctx.nav("M")}`;

    case "M-14": return `${top("รีวิวจากลูกค้า", "M-17")}${card(`<div class="row"><strong style="font-size:32px">4.8</strong><span class="muted small">คะแนนเฉลี่ย · 1,248 รีวิว</span></div>`)}<div class="list-group">${[["กมลชนก", "อาหารร้อน รสชาติเข้มข้น ส่งเร็วด้วยค่ะ"], ["ปกรณ์", "ผัดไทยอร่อยมาก กุ้งสด"], ["ณัฐชา", "ชาไทยหวานน้อยกำลังดี"]].map((x) => `<article class="review-row"><div class="row-between"><strong class="small">${x[0]}</strong><span class="review-stars" aria-label="5 ดาว">${homeIcon("star", 14).repeat(5)}</span></div><p class="small">${x[1]}</p><button class="text-btn" data-action="reply-review">ตอบกลับ</button></article>`).join("")}</div>`;

    case "M-15": { if (ctx.promoCreateMode) return `${top("สร้างโปรโมชัน", "M-15")}${heading("ตั้งค่าสิทธิพิเศษ", "กำหนดเงื่อนไขและระยะเวลาของโปรโมชัน")}${card(`${field("ชื่อโปรโมชัน", "เช่น ลด 20% สูงสุด ฿40")}${field("ยอดสั่งซื้อขั้นต่ำ (บาท)", "150", "number")}${field("ส่วนลดสูงสุด (บาท)", "40", "number")}<label class="form-field"><span>วันสิ้นสุด</span><input class="field" type="date" value="2026-10-31"></label><div class="toggle-row"><span>เปิดใช้ทันที</span><input type="checkbox" checked></div>`)}<div class="row">${button("ยกเลิก", { action: "p2-cancel-promo", variant: "ghost" })}${button("บันทึกโปรโมชัน", { action: "p2-save-promo" })}</div>`; return `${top("โปรโมชันของร้าน", "M-17")}<div class="list-group">${[["ลด 20% สูงสุด ฿40", "ยอดขั้นต่ำ ฿150 · สิ้นสุด 31 ต.ค. 2569"], ["คูปองส่งฟรี ฿15", "ใช้ได้เมื่อสั่งครบ ฿180 · 12–31 ต.ค."]].map((x, i) => `<article class="promo-row"><div class="promo-copy"><strong>${x[0]}</strong><div class="muted small">${x[1]}</div><button class="text-btn" data-action="p2-edit-promo" data-promo="${i}">แก้ไขโปรโมชัน</button></div><button class="switch ${ctx.promoPaused?.[i] ? "" : "on"}" data-action="p2-promo-toggle" data-promo="${i}" aria-label="${ctx.promoPaused?.[i] ? "เริ่ม" : "หยุด"}โปรโมชัน"></button></article>`).join("")}</div>${button("＋ สร้างโปรโมชัน", { action: "p2-create-promo" })}`; }

    case "M-16": { if (ctx.claimStep === 2) return `${top("ส่งเรื่องเคลมแล้ว", "M-17")}${card(`<strong>รับเรื่องแล้ว</strong><div class="muted small">เจ้าหน้าที่จะตรวจสอบ order ${ORDER_NO} และติดต่อกลับ</div>${button("กลับหน้าช่วยเหลือ", { action: "p2-reset-claim", variant: "secondary" })}`)}`; if (ctx.claimStep === 1) return `${top("เปิดเคลมใหม่", "M-16")}${heading("แจ้งปัญหา order", "ระบุรายการและรายละเอียดให้เจ้าหน้าที่ตรวจสอบ")}${card(`<div class="p2-upload-row">Order ${ORDER_NO} ${badge("เลือกแล้ว", "brand")}</div><div class="form-field"><label>ประเภทปัญหา</label><div class="chip-list" style="flex-wrap:wrap">${["ได้รับเมนูไม่ครบ", "อาหารเสียหาย", "ยอดเงินไม่ถูกต้อง", "อื่น ๆ"].map((t, i) => `<button class="chip ${i === 0 ? "active" : ""}" data-action="seg">${t}</button>`).join("")}</div></div>${textArea("รายละเอียด", "เล่าเหตุการณ์และสิ่งที่ต้องการให้ช่วย")}${button("＋ แนบรูปประกอบ", { action: "toast-upload", variant: "secondary" })}`)}<div class="row">${button("ย้อนกลับ", { action: "p2-reset-claim", variant: "ghost" })}${button("ส่งเคลม", { action: "p2-submit-claim" })}</div>`; return `${top("ช่วยเหลือและเคลม", "M-17")}${card(`<strong>เคส #CS-261007-128</strong>${badge("กำลังตรวจสอบ", "warning")}<div class="muted small">ลูกค้าแจ้งว่าได้รับเมนูไม่ครบ · ${ORDER_NO}</div><div class="muted micro">เปิดเคส 12:51 น. · เจ้าหน้าที่จะตอบกลับใน 30 นาที</div>${button("ดูรายละเอียด / แชทเจ้าหน้าที่", { action: "toast-support", variant: "secondary" })}`)}${section("หัวข้อช่วยเหลือ", faq([["การชำระเงินและรอบโอน", "ยอดขายโอนเข้าบัญชีทุกวันอังคารและศุกร์ หักค่าธรรมเนียมแพลตฟอร์มแล้ว"], ["ออเดอร์ถูกยกเลิก", "ดูสาเหตุได้ในรายละเอียดออเดอร์ หากไม่ถูกต้องเปิดเคลมใหม่ได้ภายใน 24 ชั่วโมง"], ["การเชื่อม Smart Kitchen", "เมนูและสต็อกซิงก์อัตโนมัติ หากไม่ตรงให้กดซิงก์ที่หน้าเชื่อมต่อ"], ["การแก้ไขข้อมูลร้าน", "แก้ชื่อ เวลาเปิดร้านและตำแหน่งได้ที่บัญชี > ข้อมูลร้าน"]]))}${button("เปิดเคลมใหม่", { action: "p2-start-claim", variant: "danger" })}`; }

    case "R-01": {
      const step = Math.max(0, Math.min(2, Number(ctx.riderSignupStep || 0)));
      const labels = ["ข้อมูลส่วนตัว", "ประเภทรถ", "เอกสาร"];
      const docs = ["บัตรประชาชน", "ใบขับขี่", "ทะเบียนรถ", "บัญชีรับเงิน"];
      const body = step === 0 ? `${field("ชื่อ-นามสกุล", PEOPLE.courier.name, "text", PEOPLE.courier.name)}${field("เบอร์โทรศัพท์", PEOPLE.courier.phone, "tel", PEOPLE.courier.phone)}` : step === 1 ? `<div class="toggle-row"><label><input type="checkbox" data-rider-type="food" ${ctx.riderTypes?.food !== false ? "checked" : ""}> ส่งอาหาร · มอเตอร์ไซค์</label></div><div class="toggle-row"><label><input type="checkbox" data-rider-type="passenger" ${ctx.riderTypes?.passenger ? "checked" : ""}> รับส่งผู้โดยสาร · รถยนต์</label></div>${ctx.riderTypes?.food !== false ? `${field("ทะเบียนรถมอเตอร์ไซค์", PEOPLE.courier.plate)}${field("รุ่น / สีรถ", PEOPLE.courier.bike)}` : ""}${ctx.riderTypes?.passenger ? `${field("ทะเบียนรถยนต์", PEOPLE.courier.carPlate)}${field("รุ่น / สีรถยนต์", PEOPLE.courier.car)}` : ""}` : docs.map((name, i) => `<div class="p2-upload-row"><span>${name}</span>${ctx.riderDocs?.includes(i) ? `<span class="pill success">แนบแล้ว · preview</span>` : badge("ยังไม่แนบ", "warning")}<button class="btn inline secondary" data-action="p2-rider-doc" data-doc="${i}">${ctx.riderDocs?.includes(i) ? "เปลี่ยน" : "แนบ"}</button></div>`).join("");
      return `${top("สมัครเป็นไรเดอร์", "A-06")}${heading("สมัครคนขับ", `ขั้นที่ ${step + 1} จาก 3 · ${labels[step]}`)}<div class="p2-progress">${labels.map((x, i) => `<div class="${i <= step ? "active" : ""}"><span>${i + 1}</span><small>${x}</small></div>`).join("")}</div>${card(body)}<div class="row">${step ? button("ย้อนกลับ", { action: "p2-wizard-back", variant: "ghost" }) : ""}${button(step === 2 ? "ส่งใบสมัคร" : "ดำเนินการต่อ", { action: step === 2 ? "toast-application" : "p2-wizard-next" })}</div>`;
    }

    case "R-03": return `${top("พร้อมออกไปทำงานไหม?", "R-10")}${card(`<div class="row-between"><div><strong>${ctx.riderOnline ? "ออนไลน์แล้ว" : "ออฟไลน์"}</strong><div class="muted small">เปิดรับงานเมื่อพร้อมออกเดินทาง</div></div></div>`)}<div class="map-card map-full"><span class="pill" style="position:absolute;top:12px;left:12px">พื้นที่ห้วยขวาง</span></div>${card(`<strong>ประเภทงานที่เปิดรับ</strong><div class="p2-task-options"><button class="toggle-row ${ctx.riderTypes?.food ? "selected" : ""}" data-action="p2-task-type" data-type="food">ส่งอาหาร · มอเตอร์ไซค์</button><button class="toggle-row ${ctx.riderTypes?.passenger ? "selected" : ""}" data-action="p2-task-type" data-type="passenger">รับส่งคน · รถยนต์</button></div><small class="muted">เปิดได้ทั้งสองประเภท แต่ทำงานได้ครั้งละหนึ่งประเภท</small>`)}<div class="metric-grid"><div class="metric"><span>รายได้วันนี้</span><strong>฿1,248</strong></div><div class="metric"><span>งานสำเร็จ</span><strong>12</strong></div></div><div class="sticky-action">${button(ctx.riderOnline ? "พักรับงาน" : "เริ่มออนไลน์", { action: "rider-online", variant: ctx.riderOnline ? "secondary" : "" })}</div>${ctx.nav("R")}`;

    case "R-06": return `${top("ตรวจสอบก่อนรับอาหาร", "R-05")}${card(`<strong>${ORDER_NO} · ${PEOPLE.merchant.name}</strong>${(ctx.orderItems || []).map((x) => `<div class="info-row"><span>${x.name}</span><strong>${x.qty} รายการ</strong></div>`).join("")}<strong class="small">ตรวจสอบก่อนออกจากร้าน</strong>${["เลข order ตรงกับใบเสร็จ", "จำนวนถุงครบ", "เครื่องดื่มแยกถุง"].map((x) => `<label class="toggle-row"><span>${x}</span><input type="checkbox" data-p2-checklist></label>`).join("")}${button("ร้านยังไม่พร้อม / ของไม่ครบ", { action: "p2-store-issue", variant: "ghost" })}`)}<div class="sticky-action">${button("ยืนยันรับอาหารแล้ว", { route: "R-07" })}</div>`;

    case "R-07": { const cash = Boolean(ctx.orderCash); return `${appBar("นำส่งอาหาร", { subtitle: ORDER_NO, back: true, route: "R-06", trailing: sosButton() })}<div class="map-card map-full"><div class="map-road" style="width:74%;top:35%;left:12%"></div><div class="map-pin" style="top:62%;left:69%;background:var(--accent)"><span>ส่ง</span></div><span class="pill" style="position:absolute;bottom:10px;left:10px">ห้วยขวาง</span><button class="icon-btn" data-action="toast-navigate" aria-label="นำทาง" title="นำทาง" style="position:absolute;right:12px;bottom:12px;width:56px;height:56px">${homeIcon("navigation", 28)}</button></div>${card(`<div class="row-between"><strong>${ORDER_NO}</strong>${badge("กำลังนำส่ง", "brand")}</div><div class="row-between"><div class="muted small">ผู้รับ · ${PEOPLE.customer.short}<br>${ADDRESS.split(",")[0]}</div><div class="row">${iconButton("call", "โทรหาลูกค้า", 'data-action="toast-call"')}${iconButton("message", "แชทกับลูกค้า", 'data-route="C-13"')}</div></div><div class="p2-customer-note"><span class="eyebrow">หมายเหตุจากลูกค้า</span><strong>${ctx.orderItems?.[0]?.note || "ไม่มีหมายเหตุเพิ่มเติม"}</strong></div>${cash ? `<div class="row-between"><span class="eyebrow">เก็บเงินสด</span><strong style="font-size:26px">${price(total)}</strong></div>` : badge("ชำระออนไลน์แล้ว", "success")}`)}<div class="sticky-action">${button("ถึงจุดส่งแล้ว", { route: "R-08" })}</div>`; }

    case "R-10": return `${top("ประวัติงาน", "R-03")}${heading("งานที่ผ่านมา", "เปิดรายการเพื่อดูรายละเอียดและรายได้")}${ctx.nav("R")}${[["อาหาร", ORDER_NO, "ครัวบ้านสวน → ห้วยขวาง", "฿72", "12:47"], ["รับส่งคน", "RM-RIDE-261007-63", "ห้วยขวาง → อโศก", "฿64", "11:20"], ["อาหาร", "RM-261007-1728", "ร้านข้าวมันไก่ → รัชดา", "฿48", "10:58"]].map((x) => rowCard(`${x[0]} · ${x[3]}`, `${x[2]} · ${x[4]} · ${x[1]}`, "", "p2-history-detail")).join("")}`;

    case "R-11": return `${top("รายได้และกระเป๋า", "R-03")}${card(`<span class="eyebrow">รายได้ที่ถอนได้</span><strong style="font-size:30px">฿4,285.50</strong><div class="muted small">ยอดโอนรอบถัดไป ศุกร์ 9 ต.ค.</div>${button("ถอนเงินเข้าบัญชี", { action: "withdraw" })}`, "tint")}${card(`<strong>เงินสดที่ต้องนำส่ง</strong><div class="row-between"><strong>฿320</strong>${badge("นำส่งภายในวันนี้", "warning")}</div><div class="muted micro">เงินสดที่รับจากลูกค้า</div>${button("ดูวิธีนำส่งเงินสด", { action: "p2-cash-remittance", variant: "secondary" })}`)}${ctx.nav("R")}`;

    case "R-14": return `${top("ช่วยเหลือและฉุกเฉิน", "R-15")}${card(`<strong>แจ้งเหตุฉุกเฉิน</strong><div class="muted small">อุบัติเหตุ · ไม่ปลอดภัย · ต้องการความช่วยเหลือ</div>${button("โทรสายด่วน 1669", { action: "emergency", variant: "danger" })}`)}${section("หัวข้อช่วยเหลือ", faq([["รายงานลูกค้าไม่รับสาย", "โทรซ้ำและรอที่จุดส่ง 3 นาที แล้วกด ติดต่อลูกค้าไม่ได้ ที่หน้ายืนยันส่ง"], ["ปัญหาที่ร้านค้า", "ถ้าของไม่ครบหรือร้านยังไม่พร้อม กดแจ้งปัญหาที่หน้าตรวจสอบก่อนรับอาหาร"], ["ชำระเงินไม่ตรง", "ตรวจยอดเงินสดที่ต้องเก็บในหน้ายืนยันส่ง แล้วแจ้งศูนย์ช่วยเหลือพร้อมเลขงาน"], ["แจ้งเหตุระหว่างทาง", "กดปุ่ม SOS มุมบนของหน้างาน ทีมช่วยเหลือจะติดต่อกลับทันที"]]))}${button("แชทเจ้าหน้าที่", { action: "toast-support", variant: "secondary" })}`;

    default: return null;
  }
}
